// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         type: "invoice",
 *         field: "mrn"
 *     }
 */
export interface DocumentLookupRequest {
    /** Document type to look up (the type defined by the bound schema). */
    type: string;
    /** Name of a lookup field declared on the schema. For a sensitive field, this body variant is required (the GET variant rejects sensitive-field lookups). */
    field: string;
    /** Exact value to match (equality mode). Mutually exclusive with `from`/`to` and `prefix`. */
    value?: string;
    /** Inclusive lower bound for a range lookup (requires `to`; non-sensitive, range-enabled fields only). Mutually exclusive with `value` and `prefix`. */
    from?: string;
    /** Inclusive upper bound for a range lookup (requires `from`; mutually exclusive with `value` and `prefix`). */
    to?: string;
    /** Prefix to match for a prefix lookup (range-enabled string fields only). Mutually exclusive with `value` and `from`/`to`. */
    prefix?: string;
    /** Pagination cursor. Pass the `nextCursor` from the previous page to fetch the next page; omit it for the first page. */
    startFrom?: string;
    /** Maximum number of documents to return per page (1–100; defaults to 20). */
    limit?: number;
    /** Sort direction for the returned results: `asc` (default) or `desc`. */
    order?: DocumentLookupRequest.Order;
}

export namespace DocumentLookupRequest {
    /** Sort direction for the returned results: `asc` (default) or `desc`. */
    export const Order = {
        Asc: "asc",
        Desc: "desc",
    } as const;
    export type Order = (typeof Order)[keyof typeof Order];
}
