// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DocumentPatchRequest {
    id: string;
    /** Human-readable document title. Omit to leave the existing title unchanged. */
    title?: string;
    /** Raw text content. Supply it to re-ingest and replace the stored text; omit it to leave the existing text unchanged. */
    text?: string;
    /** ID of the folder to place this document in. Omit to leave unchanged. */
    folderId?: string;
    /** The document's structured data, as a flat key/value object. Deep-merged into the existing payload: keys you send overwrite existing values, a key set to `null` is deleted, and keys you omit are preserved. Omit the field entirely to leave the payload unchanged. */
    payload?: Record<string, unknown>;
    /** ID of a record schema to bind this document to. Omit to leave unchanged. */
    schemaId?: string;
    /** Owning user ID. With an API key, sets the document's owner explicitly. With a scoped token the owning user is attributed by the server and cannot be changed; supplying one that conflicts is rejected. Omit to leave unchanged. */
    userId?: string;
    /** The document's scope ownership, as `namespace:value` entries (at most 2 namespaces; a value is 1-128 characters, a letter or digit first then letters/digits/`_`/`-`) — the COMPLETE new selection when supplied (`[]` clears it to the private tier). Omit to leave ownership unchanged. */
    scopes?: string[];
    /** Optimistic-concurrency token. Pass the `version` you last read to make this update conditional — rejected with `409 VERSION_CONFLICT` if the document changed since. Omit for last-write-wins. */
    expectedVersion?: number;
    /** Caller-controlled lifecycle status. `ARCHIVED` soft-retracts the document (pulled from search, kept and recoverable); `ACTIVE` restores it. Omit to leave unchanged. */
    status?: DocumentPatchRequest.Status;
}

export namespace DocumentPatchRequest {
    /** Caller-controlled lifecycle status. `ARCHIVED` soft-retracts the document (pulled from search, kept and recoverable); `ACTIVE` restores it. Omit to leave unchanged. */
    export const Status = {
        Active: "ACTIVE",
        Archived: "ARCHIVED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
