// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
 *     }
 */
export interface GetDocumentVersionsRequest {
    /** The ID of the document whose history you want. */
    id: string;
    /** Pagination cursor — pass the `nextCursor` returned by the previous page. */
    startFrom?: string;
}
