// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         type: "invoice",
 *         field: "po_number",
 *         value: "PO-1001",
 *         prefix: "PO-2024",
 *         startFrom: "550e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface LookupDocumentsRequest {
    /** The document type to look up (the `type` of the bound schema). */
    type: string;
    /** The name of the lookup field declared on the schema. */
    field: string;
    /** Exact value to match. Mutually exclusive with `from`/`to` and `prefix`. Rejected for a sensitive field — use POST /v1/documents/lookup so the value isn't exposed in the URL. */
    value?: string;
    /** Inclusive lower bound for a range lookup (requires `to`; range-enabled, non-sensitive fields only). Mutually exclusive with `value` and `prefix`. */
    from?: string;
    /** Inclusive upper bound for a range lookup (requires `from`). */
    to?: string;
    /** Prefix to match for a prefix lookup (range-enabled string fields only). Mutually exclusive with `value` and `from`/`to`. */
    prefix?: string;
    /** Pagination cursor — pass the `nextCursor` returned by the previous page. */
    startFrom?: string;
    /** Maximum number of documents to return per page (1-100; defaults to 20). */
    limit?: number;
    /** Sort direction for the returned documents: `asc` (the default) or `desc`. */
    order?: Vectros.LookupDocumentsRequestOrder;
}
