// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             title: "Patient Intake Form \u2014 Jane Doe"
 *         }
 *     }
 */
export interface PatchDocumentRequest {
    id: string;
    body: Vectros.DocumentRequest;
}
