// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             typeName: "intake_form",
 *             displayName: "Client Intake Form",
 *             description: "Captures initial client information",
 *             fields: [{
 *                     fieldId: "first_name",
 *                     fieldType: "string",
 *                     required: true,
 *                     searchable: true
 *                 }, {
 *                     fieldId: "email",
 *                     fieldType: "string",
 *                     required: true
 *                 }],
 *             lookupFields: [{
 *                     fieldName: "email",
 *                     unique: true
 *                 }],
 *             capabilities: {
 *                 "auditHistory": true
 *             },
 *             allowedSurfaces: ["record"]
 *         }
 *     }
 */
export interface CreateSchemaRequest {
    /** When `true`, if a schema with the same `typeName` already exists it is reconciled to the submitted shape (additive fields, lookups, renderHints, and `active` are applied) instead of being returned unchanged; `typeName` and migration-locked lookup attributes (`rangeEnabled`/`sortBy`/`sensitive`) cannot be changed and a request to do so is rejected. A re-applied upsert whose declared shape is unchanged is a no-op (no schema-version bump). Defaults to `false`. Requires the `schemas:w` scope. */
    upsert?: boolean;
    body: Vectros.SchemaRequest;
}
