// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
 *     }
 */
export interface DeleteSchemaRequest {
    /** The id of the schema to delete. */
    id: string;
}
