// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
 *     }
 */
export interface GetSchemaVersionsRequest {
    /** The id of the schema whose version history you want. */
    id: string;
    /** Pagination cursor — pass the `nextCursor` value from the previous page to fetch the next one. */
    startFrom?: string;
}
