// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
 *         body: {
 *             typeName: "intake_form",
 *             displayName: "Client Intake Form",
 *             allowedSurfaces: ["record"]
 *         }
 *     }
 */
export interface UpdateSchemaRequest {
    /** The id of the schema to update. */
    id: string;
    body: Vectros.SchemaRequest;
}
