// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ruleId: "3b1c9f2e7a5d8410f6c2e9a1b7d4038f5e6a91c2d7f0b3a4586c9e2f1d0a7b3c",
 *         category: "SCRIPT_ERROR",
 *         startFrom: "b3BhcXVlLWN1cnNvci1mcm9tLXRoZS1wcmV2aW91cy1wYWdl"
 *     }
 */
export interface ListTriggerFailuresRequest {
    /** Return only failures of this trigger rule. */
    ruleId?: string;
    /** Return only failures in this category (e.g. `SCRIPT_ERROR`, `TIMEOUT`, `AUTHORIZATION_DENIED`). Case-insensitive. */
    category?: string;
    /** Return only failures the platform will retry (`true`) or will not (`false`). */
    retryable?: boolean;
    /** Return only failures that first occurred at or after this ISO-8601 UTC timestamp. */
    from?: string;
    /** Return only failures that first occurred before this ISO-8601 UTC timestamp. */
    to?: string;
    /** Pagination cursor. Pass the `nextCursor` returned by the previous page to fetch the next page; omit it for the first page. The cursor is **opaque** — echo it back unchanged. */
    startFrom?: string;
    /** Maximum number of failures to return per page. Must be between 1 and 100; defaults to 20. */
    limit?: number;
}
