// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Request body for creating or updating an access profile.
 */
export interface AccessProfileRequest {
    /** Principal this profile applies to. Must start with `usr_` (an authenticated user — the suffix is the user id) or `key_` (a scoped API key acting as its own principal — the suffix is the key id). The suffix may contain only letters, digits, underscores, and hyphens. Required when creating (POST); ignored when updating (PUT), where it is taken from the path. */
    principalId: string;
    /** Inline scope clauses to grant the principal. Provide exactly one of `scopes` or `roleId` — setting both, or neither, returns a 400. */
    scopes?: Vectros.ScopeClause[] | undefined;
    /** Reference to a role within the same context that supplies this principal's scopes. Provide exactly one of `scopes` or `roleId` — setting both, or neither, returns a 400. Changes to the role's scopes take effect for all referencing profiles. */
    roleId?: string | undefined;
    /** Optional per-context identity overrides, keyed by ownership namespace in `scope:<namespace>` form — `scope:org` and `scope:client` for the reserved namespaces, or any namespace you have registered (for example `scope:group`). At most two namespaces may be overridden; any other key is rejected. Each value is 1-128 characters: a letter or digit first, then letters, digits, `_` or `-`. Omitting the field leaves any existing overrides unchanged; sending an empty map clears them, and sending a populated map replaces them wholesale — a namespace absent from the map you send is removed. If you use a scoped credential, two bounds apply and either returns 403: you may only set a value your own identity holds, and you may only change or clear a value the profile already holds if that value is yours as well — so clearing or repointing another principal's established identity is refused. A root API key (`sk_`) is exempt from both. */
    identityOverrides?: Record<string, unknown> | undefined;
    /** Profile lifecycle status. `active` permits token minting; `suspended` denies it (minting returns a uniform 403). Defaults to `active` when omitted. */
    status?: AccessProfileRequest.Status | undefined;
}

export namespace AccessProfileRequest {
    /** Profile lifecycle status. `active` permits token minting; `suspended` denies it (minting returns a uniform 403). Defaults to `active` when omitted. */
    export const Status = {
        Active: "active",
        Suspended: "suspended",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
