// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * An access profile — the permission row for one principal within one app context.
 */
export interface AccessProfileResponse {
    /** Whether this call created a new access profile. True when a new profile was created; false when a profile with the same `principalId` already existed and was returned unchanged (idempotent create) or updated (when `?upsert=true`). Present only on the create response (POST /v1/app-contexts/{contextId}/profiles); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing profile was returned. */
    created?: boolean | undefined;
    /** Opaque identifier for this profile. Also serves as the pagination cursor. */
    id?: string | undefined;
    /** The app context this profile belongs to. */
    contextId?: string | undefined;
    /** Principal this profile applies to — `usr_<userId>` for a user, or `key_<keyId>` for a scoped API key acting as its own principal. */
    principalId?: string | undefined;
    /** Inline scope clauses granted to the principal. Mutually exclusive with `roleId` — exactly one of the two is present. */
    scopes?: Vectros.ScopeClause[] | undefined;
    /** Reference to a role that supplies this principal's scopes. Mutually exclusive with `scopes` — exactly one of the two is present. */
    roleId?: string | undefined;
    /** Per-context identity overrides. Only `orgId` and `clientId` may be overridden. */
    identityOverrides?: Record<string, unknown> | undefined;
    /** Profile lifecycle status: `active` or `suspended`. */
    status?: string | undefined;
    /** When the profile was created (ISO-8601 UTC). */
    createdAt?: string | undefined;
    /** When the profile was last modified (ISO-8601 UTC). */
    lastModified?: string | undefined;
}
