// This file was auto-generated by Fern from our API Definition.

/**
 * An app context: a namespace you define to group access profiles and roles for one of your applications.
 */
export interface AppContextResponse {
    /** Whether this call created a new app context. True when a new app context was created; false when an app context with the same `contextId` already existed and was returned unchanged (idempotent create) or updated (when `?upsert=true`). Present only on the create response (POST /v1/app-contexts); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing app context was returned. */
    created?: boolean | undefined;
    /** Opaque composite identifier for this app context. Use it as the pagination cursor (pass it as `startFrom` to page through results); for everything else, refer to the app context by its `contextId`. */
    id?: string | undefined;
    /** Your identifier for the app context. */
    contextId?: string | undefined;
    /** Human-readable display name for the app context. */
    name?: string | undefined;
    /** Free-text description of the app context. */
    description?: string | undefined;
    /** Display name for the organization deploying this app context, or absent if unset. Distinct from `name` (the app's own identity) — used to personalize platform-sent correspondence (e.g. sub-user invitation emails) with your own branding. */
    companyName?: string | undefined;
    /** When the app context was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the app context was last modified, as an ISO-8601 UTC timestamp. */
    lastModified?: string | undefined;
    /** Lifecycle status of the app context: `active` under normal operation; `purging` while an asynchronous delete is draining the context's data; `deleted` once that teardown completes. After you call DELETE on an app context (which returns 202 and drains asynchronously), poll this field to observe when the teardown has finished. */
    status?: AppContextResponse.Status | undefined;
    /** The declared per-principal metering axis for this app context, or absent if unset (context-only accounting). */
    meteringAxis?: string | undefined;
    /** Per-principal, per-minute request cap for the opt-in per-principal burst-protection feature, or absent if unset. */
    principalBurstLimit?: number | undefined;
    /** Per-principal, per-billing-period operation cap for the opt-in per-principal usage/quota feature, or absent if unset (usage is still tracked for visibility/billing without a cap when `meteringAxis` is set but this is absent). */
    principalUsageCap?: number | undefined;
    /** Whether PHI read-access logging (the HIPAA §164.528 accounting of disclosures) is on by default for this context. A schema that sets `capabilities.readAccessLog` overrides it; a schema that does not inherits it. Null means no context default is set, so the platform default applies and logging is OFF. Use it to tell an empty `GET /v1/admin/access-log` result that genuinely means "no one accessed this subject" from one that means "nothing was being recorded". */
    readAccessLogDefault?: (boolean | null) | undefined;
    /** The golden IdP-asserted identity claim names projected, read-only, onto access profiles in this context. Filled in once per profile, the first time a sign-in for that principal can supply a value — usually at profile-creation, but for an invited member not until they actually accept and sign in, since there is nothing to project before that. Once filled, a profile's projection does not update again even if this declaration or the underlying identity data changes later. Absent when no projection is declared. */
    identityProjectionClaims?: string[] | undefined;
}

export namespace AppContextResponse {
    /** Lifecycle status of the app context: `active` under normal operation; `purging` while an asynchronous delete is draining the context's data; `deleted` once that teardown completes. After you call DELETE on an app context (which returns 202 and drains asynchronously), poll this field to observe when the teardown has finished. */
    export const Status = {
        Active: "active",
        Purging: "purging",
        Deleted: "deleted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
