// This file was auto-generated by Fern from our API Definition.

/**
 * An app context: a namespace you define to group access profiles and roles for one of your applications.
 */
export interface AppContextResponse {
    /** Whether this call created a new app context. True when a new app context was created; false when an app context with the same `contextId` already existed and was returned unchanged (idempotent create) or updated (when `?upsert=true`). Present only on the create response (POST /v1/app-contexts); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing app context was returned. */
    created?: boolean | undefined;
    /** Opaque composite identifier for this app context. Use it as the pagination cursor (pass it as `startFrom` to page through results); for everything else, refer to the app context by its `contextId`. */
    id?: string | undefined;
    /** Your identifier for the app context. */
    contextId?: string | undefined;
    /** Human-readable display name for the app context. */
    name?: string | undefined;
    /** Free-text description of the app context. */
    description?: string | undefined;
    /** When the app context was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the app context was last modified, as an ISO-8601 UTC timestamp. */
    lastModified?: string | undefined;
    /** Lifecycle status of the app context: `active` under normal operation; `purging` while an asynchronous delete is draining the context's data; `deleted` once that teardown completes. After you call DELETE on an app context (which returns 202 and drains asynchronously), poll this field to observe when the teardown has finished. */
    status?: AppContextResponse.Status | undefined;
}

export namespace AppContextResponse {
    /** Lifecycle status of the app context: `active` under normal operation; `purging` while an asynchronous delete is draining the context's data; `deleted` once that teardown completes. After you call DELETE on an app context (which returns 202 and drains asynchronously), poll this field to observe when the teardown has finished. */
    export const Status = {
        Active: "active",
        Purging: "purging",
        Deleted: "deleted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
