// This file was auto-generated by Fern from our API Definition.

/**
 * A single equality lookup within a batch-lookup request: find the records of a given type whose lookup field exactly matches a value.
 */
export interface BatchLookupInput {
    /** Your correlation id for this lookup, echoed back on the matching result group so you can pair results to inputs regardless of ordering. */
    ref?: string | undefined;
    /** The record type to look up. */
    type?: string | undefined;
    /** The name of the lookup field to match on, as declared on the record schema. */
    field?: string | undefined;
    /** The exact value to match against the lookup field. */
    value?: string | undefined;
}
