// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * The result for a single lookup in a batch-lookup request. Match it back to your input using the `ref` field.
 */
export interface BatchLookupResult {
    /** The correlation id echoed from the lookup input that produced this result. */
    ref?: string | undefined;
    /** The outcome for this lookup. `resolved` means exactly one match; `not_found` means no match; `ambiguous` means the field is not unique and matched more than one record. */
    status?: BatchLookupResult.Status | undefined;
    /** The matched records. Empty unless `status` is `resolved` (one record) or `ambiguous` (more than one). */
    data?: Vectros.RecordResponse[] | undefined;
}

export namespace BatchLookupResult {
    /** The outcome for this lookup. `resolved` means exactly one match; `not_found` means no match; `ambiguous` means the field is not unique and matched more than one record. */
    export const Status = {
        Resolved: "resolved",
        NotFound: "not_found",
        Ambiguous: "ambiguous",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
