// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * The result of a batch lookup: one result group per lookup you submitted. Returned with HTTP 200 even when some lookups did not resolve, so inspect each result's status.
 */
export interface BatchLookupResponse {
    /** One result group per lookup you submitted. Match each group to its input using the `ref` field. */
    results?: Vectros.BatchLookupResult[] | undefined;
}
