// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * The outcome of a single item in a batch write. Use the `index` field to match this result back to the item you submitted, since results are not guaranteed to come back in request order.
 */
export interface BatchWriteResult {
    /** Zero-based position of this item in the `items` array you submitted. Use it to correlate this result with the item you sent. */
    index?: number | undefined;
    /** The id assigned to the written record. Present when this item was created or updated; null when it failed (status `conflict` or `invalid`). */
    id?: (string | null) | undefined;
    /** The `externalId` you supplied for this item, echoed back when present. Null when the item carried no `externalId`. */
    externalId?: (string | null) | undefined;
    /** The outcome for this item. `created` and `updated` are successes; `conflict` is a uniqueness or version conflict; `invalid` is a validation failure. */
    status?: BatchWriteResult.Status | undefined;
    error?: (Vectros.BatchItemError | null) | undefined;
}

export namespace BatchWriteResult {
    /** The outcome for this item. `created` and `updated` are successes; `conflict` is a uniqueness or version conflict; `invalid` is a validation failure. */
    export const Status = {
        Created: "created",
        Updated: "updated",
        Conflict: "conflict",
        Invalid: "invalid",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
