// This file was auto-generated by Fern from our API Definition.

/**
 * A single field's before/after values within an audit-history diff.
 */
export interface ChangedField {
    /** Name of the changed field. */
    name?: string | undefined;
    /** Field value before the change (type depends on the field). */
    sourceVal?: Record<string, unknown> | undefined;
    /** Field value after the change (type depends on the field). */
    targetVal?: Record<string, unknown> | undefined;
}
