// This file was auto-generated by Fern from our API Definition.

/**
 * The conversation history, in order. A message with role `system` is extracted and used as the system prompt; `user` and `assistant` messages are sent to the model as conversation turns.
 */
export interface ChatMessage {
    /** The role of this message. `system` is extracted and used as the system prompt; `user` and `assistant` are sent as conversation turns. */
    role: ChatMessage.Role;
    /** The text content of the message. */
    content: string;
}

export namespace ChatMessage {
    /** The role of this message. `system` is extracted and used as the system prompt; `user` and `assistant` are sent as conversation turns. */
    export const Role = {
        System: "system",
        User: "user",
        Assistant: "assistant",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
