// This file was auto-generated by Fern from our API Definition.

/**
 * A client (subject) identity that you control.
 */
export interface ClientResponse {
    /** The Vectros-assigned UUID for this client. Use this ID when referencing the client in token minting, record ownership, and filters. */
    id?: string | undefined;
    /** Your own identifier for this client, supplied when it was created. */
    externalId?: string | undefined;
    /** Display name for this client. */
    name?: string | undefined;
    /** Lifecycle status of the client. `ACTIVE` clients can be used normally; `SUSPENDED` clients are retained but blocked from new operations. */
    status?: string | undefined;
    /** The Vectros-assigned UUID of the organization this client belongs to, or null if the client is not associated with an org. */
    orgId?: string | undefined;
    /** Free-form key-value attributes stored with this client. Sensitive fields are returned as `[redacted]` unless your token grants the sensitive-reveal scope for the client's schema. */
    payload?: Record<string, unknown> | undefined;
    /** The ID of the schema that validates this client's payload and drives its lookup indexing, or null if the client is not schema-bound. */
    schemaId?: string | undefined;
    /** The version of the governing schema that was in effect when this client was last written. The client keeps the version it was stamped with even after the schema is edited. Null when the client is not schema-bound. */
    schemaVersion?: number | undefined;
    /** When the client was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
}
