// This file was auto-generated by Fern from our API Definition.

/**
 * A streamed chunk of generated model output. Concatenate the `delta` values in arrival order to reconstruct the full response.
 */
export interface ContentDeltaEvent {
    /** Backward-compatible alias of `type`. Always `content_delta`. */
    event: ContentDeltaEvent.Event;
    /** The next chunk of generated text. */
    delta: string;
}

export namespace ContentDeltaEvent {
    /** Backward-compatible alias of `type`. Always `content_delta`. */
    export const Event = {
        ContentDelta: "content_delta",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
}
