// This file was auto-generated by Fern from our API Definition.

/**
 * Operation count and the credits charged for them
 */
export interface CountAndCredits {
    /** Number of operations this period */
    count?: number | undefined;
    /** Credits charged for these operations (rounded down) */
    credits?: number | undefined;
    /** credits in milli-credit precision (exact, 1 credit = 1000 milli-credits) */
    creditsMilli?: number | undefined;
}
