// This file was auto-generated by Fern from our API Definition.

/**
 * Per-category credit decomposition for the period. Each category has both a rounded value (for display) and a *Milli value (for exact math).
 */
export interface CreditBreakdown {
    /** Credits consumed by search queries */
    searchQueries?: number | undefined;
    /** searchQueries in milli-credit precision (exact) */
    searchQueriesMilli?: number | undefined;
    /** Credits consumed by ingesting documents/records into search indices */
    searchIngest?: number | undefined;
    /** searchIngest in milli-credit precision (exact) */
    searchIngestMilli?: number | undefined;
    /** Credits consumed by document downloads */
    documents?: number | undefined;
    /** documents in milli-credit precision (exact) */
    documentsMilli?: number | undefined;
    /** Credits consumed by record writes */
    records?: number | undefined;
    /** records in milli-credit precision (exact) */
    recordsMilli?: number | undefined;
    /** Credits consumed by identity (user/org/client) writes */
    identity?: number | undefined;
    /** identity in milli-credit precision (exact) */
    identityMilli?: number | undefined;
    /** Estimated storage credits this period (final billing runs at cycle end) */
    storageEstimate?: number | undefined;
    /** storageEstimate in milli-credit precision (exact) */
    storageEstimateMilli?: number | undefined;
    /** Credits consumed by read-call overage */
    reads?: number | undefined;
    /** reads in milli-credit precision (exact) */
    readsMilli?: number | undefined;
    /** Credits consumed by data-out (egress) overage — includes document downloads */
    dataOut?: number | undefined;
    /** dataOut in milli-credit precision (exact) */
    dataOutMilli?: number | undefined;
}
