// This file was auto-generated by Fern from our API Definition.

/**
 * Identity binding for a scoped key. `userId`, `orgId`, or both may be present.
 */
export interface DataScope {
    /** Bound user id. The credential can only access records owned by this user. */
    userId?: string | undefined;
    /** Bound org id. The credential can only access records owned by this org. */
    orgId?: string | undefined;
}
