// This file was auto-generated by Fern from our API Definition.

/**
 * The raw stored text body of a document.
 */
export interface DocumentTextResponse {
    /** Document ID. */
    id?: string | undefined;
    /** Full extracted or ingested text content of the document. */
    text?: string | undefined;
}
