// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for creating or updating a text-ingested document. Update semantics (PUT): omitted fields are preserved — sending null does not clear a field; `payload` is replaced in full when supplied (not deep-merged); `indexMode` is fixed at creation and ignored on update; `text` is used only on the POST ingest path.
 */
export interface DocumentRequest {
    /** Human-readable document title */
    title: string;
    /** Raw text content to ingest. Required when creating a document via the text-ingest path. On update, supply it to replace the stored text; omit it to leave the existing text unchanged. */
    text?: string | undefined;
    /** Indexing strategy for this document. `HYBRID` runs both BM25 keyword and dense-vector semantic indexing (recommended for most use cases). `SEMANTIC` indexes only as dense vectors — best for conceptual similarity search. `TEXT` indexes only with BM25 — best for exact keyword matching. `NONE` stores the document without search indexing (store-only / archival): it remains retrievable by id and by structured-field lookup but never appears in search results. Optional: omit to inherit the bound schema's default index mode. If neither this field nor the schema specifies one, the request is rejected. When both are set, this per-document value wins. */
    indexMode?: DocumentRequest.IndexMode | undefined;
    /** If true, the raw text is retained so you can later fetch it via `GET /v1/documents/{id}/text`. Defaults to false to minimize storage costs. */
    storeText?: boolean | undefined;
    /** ID of the folder to place this document in. On create, omit to use your account's default root folder. On update, omit to leave unchanged — this field cannot currently be cleared once set. */
    folderId?: string | undefined;
    /** The document's structured data, as a flat key/value object. When `schemaId` is set, declared fields are validated against the schema and its lookup fields become directly queryable via `GET /v1/documents?type=&field=&value=` (sensitive fields are blind-indexed); undeclared keys pass through as free-form and are searchable via the `filters` parameter on `POST /v1/search`. A strict schema rejects undeclared keys. On update, the supplied object replaces the stored payload in full (it is not key-merged); omit to leave it unchanged. */
    payload?: Record<string, unknown> | undefined;
    /** Optional ID of a record schema to bind this document to. When set, the document's `payload` is validated against the schema's fields on save, and the schema's lookup fields become directly queryable (the same behavior as records). On update, omit to leave unchanged. */
    schemaId?: string | undefined;
    /** Owning user ID — the Vectros-assigned UUID of a user in your account. Optional. With an API key, sets the document's owner explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope. */
    userId?: string | undefined;
    /** Owning organization ID — the Vectros-assigned UUID of an organization in your account. Optional. With an API key, sets the document's owning organization explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope. */
    orgId?: string | undefined;
    /** Associated client ID — the Vectros-assigned UUID of a client in your account. Optional. With an API key, sets the document's client explicitly. With a scoped token, must match the token's identity claim (if set) or fall within its data scope. */
    clientId?: string | undefined;
    /** Stable, caller-supplied identifier for this document. Optional. Immutable after create. Unique within your account and context: posting again with the same `externalId` returns the existing document (idempotent ingest), and it is the key other records use to reference this one. Max 256 characters. */
    externalId?: string | undefined;
    /** Optimistic-concurrency token. Pass the `version` you last read (from a GET or a prior write response) to make this update conditional — it is rejected with `409 VERSION_CONFLICT` if the document was modified since, leaving the stored document untouched. Omit for last-write-wins (the default). Ignored on create. */
    expectedVersion?: number | undefined;
}

export namespace DocumentRequest {
    /** Indexing strategy for this document. `HYBRID` runs both BM25 keyword and dense-vector semantic indexing (recommended for most use cases). `SEMANTIC` indexes only as dense vectors — best for conceptual similarity search. `TEXT` indexes only with BM25 — best for exact keyword matching. `NONE` stores the document without search indexing (store-only / archival): it remains retrievable by id and by structured-field lookup but never appears in search results. Optional: omit to inherit the bound schema's default index mode. If neither this field nor the schema specifies one, the request is rejected. When both are set, this per-document value wins. */
    export const IndexMode = {
        Hybrid: "HYBRID",
        Semantic: "SEMANTIC",
        Text: "TEXT",
        None: "NONE",
    } as const;
    export type IndexMode = (typeof IndexMode)[keyof typeof IndexMode];
}
