// This file was auto-generated by Fern from our API Definition.

/**
 * Presigned download URL for a file-backed document.
 */
export interface DocumentDownloadResponse {
    /** Document ID. */
    id?: string | undefined;
    /** Presigned download URL for the original file. Short-lived — fetch the file before the time given in `expires`. */
    downloadUrl?: string | undefined;
    /** Epoch-millis (Unix milliseconds) timestamp at which the presigned URL expires. */
    expires?: number | undefined;
    /** MIME type of the file, as captured at upload time. */
    fileType?: string | undefined;
}
