// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Document storage bytes by ingest path
 */
export interface DocumentStorage {
    text?: Vectros.StorageEntry | undefined;
    file?: Vectros.StorageEntry | undefined;
}
