// This file was auto-generated by Fern from our API Definition.

/**
 * Terminal event emitted after the model finishes or the stream ends cleanly. Reports total token usage and the billing breakdown for this call.
 */
export interface DoneEvent {
    /** Backward-compatible alias of `type`. Always `done`. */
    event: DoneEvent.Event;
    /** Total input tokens consumed by the model, including the system prompt and all messages. */
    inputTokens: number;
    /** Total output tokens generated by the model. */
    outputTokens: number;
    /** The model alias used for this call. */
    model: string;
    /** Credits debited from your monthly plan allowance for this call's per-call platform overhead. One credit equals one cent. */
    platformCreditsCharged: number;
    /** Cents debited from your pre-paid inference balance for the model's token cost. */
    inferenceBalanceCentsCharged: number;
    /** Number of input tokens served from the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility. */
    cacheReadTokens?: number | undefined;
    /** Number of tokens written to the prompt cache. Present only when prompt caching applied to this call. Prompt caching is not yet used; this field is reserved for forward compatibility. */
    cacheCreateTokens?: number | undefined;
}

export namespace DoneEvent {
    /** Backward-compatible alias of `type`. Always `done`. */
    export const Event = {
        Done: "done",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
}
