// This file was auto-generated by Fern from our API Definition.

/**
 * Pre-signed download URL usage. Document-download egress is metered as part of the unified data-out line: it draws your plan's included data-out allowance and is billed at the data-out rate above it — see `reads.dataOut`. This section is the document-download byte detail; its `credits` is always 0 (the charge appears on the data-out line, not here).
 */
export interface Downloads {
    /** Total bytes egressed via download URLs this period (also counted toward `reads.dataOut.bytes`) */
    bytes?: number | undefined;
    /** Always 0 — document downloads are billed on the unified data-out line (`reads.dataOut`), not as a separate per-download charge. */
    credits?: number | undefined;
}
