// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for creating or updating an identity entity. The namespace comes from the URL path. On update (PUT), omitted fields are preserved — a null value does not clear a field — and the `payload` object is replaced in full when supplied, rather than deep-merged.
 */
export interface EntityRequest {
    /** Your own unique identifier for this entity, unique within its namespace. Used for idempotent create: if an entity with this `externalId` already exists in the namespace, it is returned instead of creating a duplicate. */
    externalId: string;
    /** Human-readable name for the entity. */
    name?: string | undefined;
    /** Lifecycle status of the entity. `ACTIVE` entities can be used normally; `SUSPENDED` entities are retained but blocked from new operations. */
    status?: EntityRequest.Status | undefined;
    /** Free-form key-value attributes to store with the entity. On update, the supplied object replaces the stored payload in full (it is not key-merged); omit it to leave the stored payload unchanged. */
    payload?: Record<string, unknown> | undefined;
    /** Optional ID of a record schema (created via `POST /v1/schemas`) that governs payload validation and lookup indexing for this entity, and must belong to your account. */
    schemaId?: string | undefined;
    /** The entity's parent ownership edges, each as `<namespace>:<value>` (for example `org:6ba7b810-...`). At most two parents, each in a DIFFERENT namespace from the entity's own. On update, providing `scopes` REPLACES the full set of parents; omit it to leave ownership unchanged. The entity's own reference (`<its namespace>:<its id>`) is accepted and ignored, so you can send back the `scopes` you read from a GET unchanged; any OTHER value in its own namespace is rejected, because a parent edge always crosses namespaces — a value in this entity's own namespace names a peer, not a parent. */
    scopes?: string[] | undefined;
}

export namespace EntityRequest {
    /** Lifecycle status of the entity. `ACTIVE` entities can be used normally; `SUSPENDED` entities are retained but blocked from new operations. */
    export const Status = {
        Active: "ACTIVE",
        Suspended: "SUSPENDED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
