// This file was auto-generated by Fern from our API Definition.

/**
 * Deletion counts for a single erased context.
 */
export interface ErasureContextResult {
    /** The context that was erased. */
    contextId?: string | undefined;
    /** Number of records deleted in this context. */
    recordsDeleted?: number | undefined;
    /** Number of documents deleted in this context. */
    documentsDeleted?: number | undefined;
    /** Number of folders deleted in this context. */
    foldersDeleted?: number | undefined;
    /** Number of identity rows deleted: 1 for the subject's user or identity-entity record (its lookup rows are removed with it but not counted). Because the subject's identity is account-wide rather than per-context, it is counted only once here — against the first context swept — and only when the identity was deleted; otherwise it is 0 everywhere and the certificate's `identityRetained` is true. */
    identityRowsDeleted?: number | undefined;
}
