// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Job handle and result for an asynchronous data-export request. While the job runs this carries its status; once it completes it also carries a short-lived presigned download URL and a manifest describing the exported payload.
 */
export interface ExportRequestResponse {
    /** Opaque identifier for the export job. Pass this to `GET /v1/admin/export/{id}` to poll for status and, once complete, the download URL. */
    exportJobId?: string | undefined;
    /** Current status of the job. `accepted` immediately after submission, then `processing` while the export runs, then either `completed` (the download URL and manifest are populated) or `failed` (see `failureReason`). */
    status?: ExportRequestResponse.Status | undefined;
    /** Echoes the scope you requested: `tenant` for a full export of your account, or `subject` for a single end-subject's data. */
    scope?: ExportRequestResponse.Scope | undefined;
    /** For a `subject`-scoped export, the kind of subject that was exported (echoed back). Null for a `tenant`-scoped export. */
    subjectType?: ExportRequestResponse.SubjectType | undefined;
    /** For a `subject`-scoped export, the resolved platform id of the exported subject (echoed back). Null for a `tenant`-scoped export. */
    subjectId?: string | undefined;
    /** When the job was accepted, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the export finished, as an ISO-8601 UTC timestamp. Null until `status` is `completed`. */
    completedAt?: string | undefined;
    /** Short-lived presigned URL for downloading the serialized export payload. Present once `status` is `completed`; null while the job is accepted or processing. Treat it as a secret — anyone with the URL can download the data until it expires. */
    downloadUrl?: string | undefined;
    /** When the presigned download URL expires, as an ISO-8601 UTC timestamp. Poll the job again after this time to obtain a fresh URL. Null until `status` is `completed`. */
    expiresAt?: string | undefined;
    /** Reason the export failed, suitable for display or programmatic handling. Present only when `status` is `failed`; null otherwise. */
    failureReason?: string | undefined;
    manifest?: Vectros.ExportManifest | undefined;
}

export namespace ExportRequestResponse {
    /** Current status of the job. `accepted` immediately after submission, then `processing` while the export runs, then either `completed` (the download URL and manifest are populated) or `failed` (see `failureReason`). */
    export const Status = {
        Accepted: "accepted",
        Processing: "processing",
        Completed: "completed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Echoes the scope you requested: `tenant` for a full export of your account, or `subject` for a single end-subject's data. */
    export const Scope = {
        Tenant: "tenant",
        Subject: "subject",
    } as const;
    export type Scope = (typeof Scope)[keyof typeof Scope];
    /** For a `subject`-scoped export, the kind of subject that was exported (echoed back). Null for a `tenant`-scoped export. */
    export const SubjectType = {
        User: "user",
        Client: "client",
        Org: "org",
    } as const;
    export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];
}
