// This file was auto-generated by Fern from our API Definition.

/**
 * Describes a completed export: the payload's serialization format and version, plus a per-context summary of what it contains.
 */
export interface ExportManifest {
    /** Schema version of the manifest and payload, for forward-compatible parsing. It is bumped whenever the exported row schema changes, so branch your parsing logic on this value. */
    formatVersion?: string | undefined;
    /** Serialization format of the payload. NDJSON (newline-delimited JSON, one row per line) is currently the only supported format. */
    format?: ExportManifest.Format | undefined;
    /** Total uncompressed size of the export payload, in bytes. */
    sizeBytes?: number | undefined;
    /** The context ids included in this export. */
    contextsExported?: string[] | undefined;
    /** Total number of records included across all exported contexts. */
    totalRecords?: number | undefined;
    /** Total number of documents included across all exported contexts. */
    totalDocuments?: number | undefined;
    /** Total number of folders included across all exported contexts. */
    totalFolders?: number | undefined;
    /** Total number of identity rows included (users, organizations, and clients). */
    totalIdentities?: number | undefined;
}

export namespace ExportManifest {
    /** Serialization format of the payload. NDJSON (newline-delimited JSON, one row per line) is currently the only supported format. */
    export const Format = {
        Ndjson: "ndjson",
    } as const;
    export type Format = (typeof Format)[keyof typeof Format];
}
