// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a single field's type, validation, and indexing behavior.
 */
export interface FieldDef {
    /** Unique identifier for this field within the schema. */
    fieldId: string;
    /** Data type of the field. Use `reference` for a foreign-key field that points at another type — then set `targetTypeName`, `targetField`, `targetSurface`, and `cardinality` below. */
    fieldType: FieldDef.FieldType;
    /** Whether this field is required when a record is created. */
    required?: boolean | undefined;
    /** Whether this field's value contributes to full-text search. */
    searchable?: boolean | undefined;
    /** Whether this field can be used as a filter in queries. */
    filterable?: boolean | undefined;
    /** Human-readable description of the field. */
    description?: string | undefined;
    /** Validation rules for this field's value (such as minimum/maximum length or a regex pattern). */
    validation?: Record<string, unknown> | undefined;
    /** The set of allowed values, for an enum-type field. */
    enumValues?: Record<string, unknown>[] | undefined;
    /** For a `reference` field: the target type this field points at. Required for reference fields. */
    targetTypeName?: string | undefined;
    /** For a `reference` field: the target's lookup field to resolve against. Defaults to `externalId`, and must name a unique lookup on the target type. */
    targetField?: string | undefined;
    /** For a `reference` field: `one` (a single id, the default) or `many` (an array of ids). */
    cardinality?: string | undefined;
    /** For a `reference` field: where the target lives — `record`, `document`, `user`, or the name of an identity namespace (`org`, `client`, or one you registered, such as `team`). Required for reference fields. The same type name can exist in more than one place, so this disambiguates which lookup resolves the reference. A namespace must already be registered and entity-backed, otherwise the schema is rejected — a reference that could never resolve fails when you define it, not on every write. */
    targetSurface?: string | undefined;
    /** Marks the field as sensitive (PHI/PII). Sensitive fields are redacted in logs, audit trails, and errors; blind-indexed for lookups; excluded from search; and masked in responses unless the token carries the `s` reveal scope for this record type. */
    sensitive?: boolean | undefined;
}

export namespace FieldDef {
    /** Data type of the field. Use `reference` for a foreign-key field that points at another type — then set `targetTypeName`, `targetField`, `targetSurface`, and `cardinality` below. */
    export const FieldType = {
        String: "string",
        Number: "number",
        Boolean: "boolean",
        Date: "date",
        Enum: "enum",
        Array: "array",
        Object: "object",
        Reference: "reference",
    } as const;
    export type FieldType = (typeof FieldType)[keyof typeof FieldType];
}
