// This file was auto-generated by Fern from our API Definition.

/**
 * Response containing the presigned upload URL and the assigned document ID.
 */
export interface FileUploadResponse {
    /** Document ID assigned to this upload. Poll `GET /v1/documents/{id}` to track indexing status after the upload completes. */
    id?: string | undefined;
    /** Presigned upload URL. Upload the raw file bytes directly to this URL with an HTTP PUT request, setting the Content-Type header to the `fileType` you provided. No Authorization header is needed — the URL is self-authenticating. */
    uploadUrl?: string | undefined;
    /** ISO-8601 UTC timestamp at which the presigned URL expires. The upload must complete before this time. Default expiry is 60 minutes. */
    expiresAt?: string | undefined;
    /** The stable identifier you supplied on the request, echoed back. Immutable, and unique within your account and context. Null when you did not supply one. */
    externalId?: string | undefined;
}
