// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Operator map for one field. Operators are AND-combined; $in/$nin take an array operand and may not be combined with other operators. Mirrors the documented closed operator set on SearchRequest.filters.
 */
export interface FilterCondition {
    /** Equals the given scalar. */
    $eq?: Vectros.Scalar | undefined;
    /** Not equal to the given scalar. */
    $ne?: Vectros.Scalar | undefined;
    /** Strictly greater than the given scalar. */
    $gt?: Vectros.Scalar | undefined;
    /** Greater than or equal to the given scalar. */
    $gte?: Vectros.Scalar | undefined;
    /** Strictly less than the given scalar. */
    $lt?: Vectros.Scalar | undefined;
    /** Less than or equal to the given scalar. */
    $lte?: Vectros.Scalar | undefined;
    /** Matches any value in the array (membership). */
    $in?: Vectros.Scalar[] | undefined;
    /** Matches none of the values in the array (negated membership). */
    $nin?: Vectros.Scalar[] | undefined;
}
