// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for creating or updating a folder. On update (PUT or PATCH), omitted fields are preserved — a null does not clear a field. `parentFolderId` is honored only at creation and ignored on update, because a folder cannot currently be moved via the API.
 */
export interface FolderRequest {
    /** Human-readable display name of the folder. Required. */
    name: string;
    /** Optional description of the folder's contents or purpose. */
    description?: string | undefined;
    /** ID of the parent folder to create this folder under, applied at creation only. Omit to create the folder under your context's default root folder. Ignored on update: a folder cannot currently be moved via the API. */
    parentFolderId?: string | undefined;
    /** Optional stable slug for the folder, unique among its siblings under the same parent. Useful as an idempotency key so re-creating the same folder returns the existing one rather than a duplicate. Derived from the name when omitted. Must be lowercase letters, digits, and hyphens. Immutable once the folder is created. */
    slug?: string | undefined;
    /** Optional ID of the user that should own this folder — the Vectros-assigned UUID of a user in your account. With an API key, this sets the folder's owner directly. With a scoped token, it must match the token's identity claim (if one is set) or fall within the token's data scope. */
    userId?: string | undefined;
    /** The folder's scope ownership, as `namespace:value` entries (at most 2 namespaces) — for example `["org:6ba7b810-9dad-11d1-80b4-00c04fd430c8", "group:eng-team"]`. `org` and `client` are built-in namespaces; others are custom scopes you define (lowercase, 2-32 chars). Resolve a namespace's UUID from your own identifier with `GET /v1/entities/{namespace}?externalId=`. When supplied, this is the folder's COMPLETE scope declaration: for a token that stamps identity, entries must match the token's identity values, and an empty array creates a folder owned by the calling user alone (the private tier). Omit the field to inherit the token's full identity — the default. On update, omit to leave ownership unchanged, or supply the complete new selection (`[]` clears it). */
    scopes?: string[] | undefined;
    /** Optimistic-concurrency token for updates. Pass the `version` you last read to make the update conditional — it is rejected with a 409 version conflict (and the stored folder is left untouched) if the folder changed since. Omit for last-write-wins (the default). Ignored on create. */
    expectedVersion?: number | undefined;
}
