// This file was auto-generated by Fern from our API Definition.

/**
 * A folder used to organize your documents and records.
 */
export interface FolderResponse {
    /** Present only on a create response: `true` when a new folder was created (HTTP 201), `false` when a folder with the same slug already existed under the same parent and was returned instead (HTTP 200). Omitted on reads, lists, and updates. */
    created?: boolean | undefined;
    /** Unique identifier for the folder, assigned by Vectros. */
    id?: string | undefined;
    /** Human-readable display name of the folder. */
    name?: string | undefined;
    /** Optional description of the folder's contents or purpose. */
    description?: string | undefined;
    /** ID of this folder's parent. Null when the folder is a root folder. */
    parentFolderId?: string | undefined;
    /** Stable URL-safe slug for the folder, unique among its siblings under the same parent. Assigned at creation and immutable thereafter. */
    slug?: string | undefined;
    /** How deeply the folder is nested. A root folder has depth 0; each level below increments by 1. */
    depth?: number | undefined;
    /** Whether this folder is protected from deletion. Your context's root folder is protected. */
    isProtected?: boolean | undefined;
    /** ID of the user that owns this folder — the Vectros-assigned UUID of a user in your account. Null if the folder is not owned by a specific user. */
    userId?: string | undefined;
    /** The folder's scope ownership as canonical `namespace:value` entries (at most 2). `org` and `client` are built-in namespaces; any other is a custom scope you define. Set at creation, either explicitly or automatically from the calling token's identity. Empty for a folder owned by a user alone (or unowned). */
    scopes?: string[] | undefined;
    /** When the folder was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the folder was last modified, as an ISO-8601 UTC timestamp. */
    lastModified?: string | undefined;
    /** Optimistic-concurrency version, incremented on every successful write. Pass it back as `expectedVersion` on a later update or patch to avoid silently overwriting a concurrent change — the write is rejected with a 409 version conflict if the folder has changed since. */
    version?: number | undefined;
}
