// This file was auto-generated by Fern from our API Definition.

/**
 * A folder used to organize your documents and records.
 */
export interface FolderResponse {
    /** Unique identifier for the folder, assigned by Vectros. */
    id?: string | undefined;
    /** Human-readable display name of the folder. */
    name?: string | undefined;
    /** Optional description of the folder's contents or purpose. */
    description?: string | undefined;
    /** ID of this folder's parent. Null when the folder is a root folder. */
    parentFolderId?: string | undefined;
    /** Stable URL-safe slug for the folder, unique among its siblings under the same parent. Assigned at creation and immutable thereafter. */
    slug?: string | undefined;
    /** How deeply the folder is nested. A root folder has depth 0; each level below increments by 1. */
    depth?: number | undefined;
    /** Whether this folder is protected from deletion. Your context's root folder is protected. */
    isProtected?: boolean | undefined;
    /** ID of the user that owns this folder — the Vectros-assigned UUID of a user in your account. Null if the folder is not owned by a specific user. */
    userId?: string | undefined;
    /** ID of the organization that owns this folder — the Vectros-assigned UUID of an organization in your account. Null if the folder is not owned by a specific organization. */
    orgId?: string | undefined;
    /** ID of the client associated with this folder — the Vectros-assigned UUID of a client in your account. Null if the folder is not associated with a specific client. */
    clientId?: string | undefined;
    /** When the folder was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the folder was last modified, as an ISO-8601 UTC timestamp. */
    lastModified?: string | undefined;
    /** Optimistic-concurrency version, incremented on every successful write. Pass it back as `expectedVersion` on a later update or patch to avoid silently overwriting a concurrent change — the write is rejected with a 409 version conflict if the folder has changed since. */
    version?: number | undefined;
}
