// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Identity write + storage activity, broken down per identity surface. Each surface mirrors the record shape: a write count (base + schema-lookup-field writes) and a storage line at the record rate.
 */
export interface IdentitySection {
    users?: Vectros.IdentitySurface | undefined;
    orgs?: Vectros.IdentitySurface | undefined;
    clients?: Vectros.IdentitySurface | undefined;
}
