// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Per-endpoint inference call stats
 */
export interface InferenceEndpoints {
    chat?: Vectros.InferenceCallStats | undefined;
    rag?: Vectros.InferenceCallStats | undefined;
    ask?: Vectros.InferenceCallStats | undefined;
}
