// This file was auto-generated by Fern from our API Definition.

/**
 * Ingest count, bytes, and credits for a single mode
 */
export interface IngestEntry {
    /** Number of ingest operations */
    count?: number | undefined;
    /** Bytes ingested */
    bytes?: number | undefined;
    /** Credits charged for these ingests (rounded down) */
    credits?: number | undefined;
    /** credits in milli-credit precision (exact) */
    creditsMilli?: number | undefined;
}
