// This file was auto-generated by Fern from our API Definition.

/**
 * A minted scoped token and its absolute expiration. The token is an opaque string for use in `Authorization: Bearer <token>` headers; `expiresAt` mirrors the token's `exp` claim (seconds since the Unix epoch) so you can decide when to refresh without decoding the token.
 */
export interface MintTokenResponse {
    /** The opaque bearer token. Send it as `Authorization: Bearer <token>` on subsequent requests. */
    token: string;
    /** When the token expires, as seconds since the Unix epoch (matches the token's `exp` claim). */
    expiresAt: number;
}
