// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A single page of version-history entries, returned by the `.../versions` endpoints. The `data` array holds the entries. `nextCursor` is an opaque cursor you pass to fetch the next page; it is null when no more pages remain.
 */
export interface ModelDataVersionPage {
    /** The items on this page, in the endpoint's natural order. Empty when there are no results. */
    data?: Vectros.ModelDataVersionResponse[] | undefined;
    /** An opaque cursor for the next page. Pass it back as the `startFrom` query parameter to continue paging; null when there are no more results. Treat it as opaque — do not parse or construct it. */
    nextCursor?: (string | null) | undefined;
}
