// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A single entry in a record's audit-trail version history. Returned by GET /v1/records/{id}/versions.
 */
export interface ModelDataVersionResponse {
    /** Unique identifier for this version-history entry. */
    id?: string | undefined;
    /** The kind of change this entry records: CREATE for the initial creation, UPDATE for a mutation, DELETE for a deletion. */
    changeType?: ModelDataVersionResponse.ChangeType | undefined;
    /** A JSON-encoded snapshot of the record's full state immediately before this change. Deserialize it to inspect the previous payload, ownership, and other fields. Present on UPDATE and DELETE entries; null on CREATE. */
    previousContent?: string | undefined;
    /** The record's version number immediately before this change. Null on CREATE. */
    previousVersion?: number | undefined;
    /** A short, system-generated description of what changed. */
    changeReason?: string | undefined;
    /** Identifier of the user or API key that made the change. */
    changedBy?: string | undefined;
    /** Time this version-history entry was recorded, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    changedFields?: Vectros.ModelChanges | undefined;
}

export namespace ModelDataVersionResponse {
    /** The kind of change this entry records: CREATE for the initial creation, UPDATE for a mutation, DELETE for a deletion. */
    export const ChangeType = {
        Create: "CREATE",
        Update: "UPDATE",
        Delete: "DELETE",
    } as const;
    export type ChangeType = (typeof ChangeType)[keyof typeof ChangeType];
}
