// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * The list of available inference models plus the default model alias.
 */
export interface ModelsResponse {
    /** The available inference models. */
    models: Vectros.ModelInfo[];
    /** Model alias used when a request omits the `model` field. */
    defaultModel: string;
}
