// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * The available inference models.
 */
export interface ModelInfo {
    /** Stable model alias. Pass this as the `model` field on `/v1/chat` and other inference endpoints. */
    id: string;
    /** Human-readable display name for the model. */
    name: string;
    /** Name of the model vendor (for example, Anthropic or AWS), suitable for display in a model picker. */
    provider: string;
    /** Maximum context window, in tokens. */
    contextWindow: number;
    /** Plan tiers on which this model is available (a subset of: free, starter, pro, scale, enterprise). */
    availableOn: string[];
    /** Base (non-US) credit rate per 1K input tokens; 1 credit = 1 cent. Requests are served from a US region by default and billed `regionPricing.us` (this value multiplied by `regionPremiumFactor`). See `regionPricing` for both the US and base rates. */
    inputCreditsPer1kTokens: number;
    /** Base (non-US) credit rate per 1K output tokens; 1 credit = 1 cent. The default US-served rate is this value multiplied by `regionPremiumFactor`; see `regionPricing` for both rates. */
    outputCreditsPer1kTokens: number;
    regionPricing: Vectros.RegionPricing;
}
