// This file was auto-generated by Fern from our API Definition.

/**
 * A scope-namespace registration — declares whether values in the namespace resolve to identity entities. The reserved namespaces `org` and `client` are always present as built-ins.
 */
export interface NamespaceResponse {
    /** The registered namespace. */
    namespace?: string | undefined;
    /** Whether values in this namespace must resolve to an existing identity entity (`true`) or are free-form strings (`false`). */
    entityBacked?: boolean | undefined;
    /** Whether this is a reserved built-in namespace (`org`/`client`). Built-ins cannot be changed or deleted. */
    reserved?: boolean | undefined;
    /** ID of the default record schema bound to entities in this namespace, or null. */
    defaultSchemaId?: string | undefined;
    /** This namespace's position in your account's specificity order (higher = more specific), used to break a tie when a caller holds two scope dimensions at once during recordType schema resolution. */
    specificityRank?: number | undefined;
    /** Timestamp when the namespace was registered, as an ISO-8601 UTC timestamp. Absent for the reserved built-ins. */
    createdAt?: string | undefined;
}
