// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Query counts and credits by search mode
 */
export interface QueryCounts {
    text?: Vectros.CountAndCredits | undefined;
    semantic?: Vectros.CountAndCredits | undefined;
    hybrid?: Vectros.CountAndCredits | undefined;
}
