// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A single Server-Sent Event from `POST /v1/rag`. The `type` field discriminates which event type this is (the `event` field carries the same value for backward compatibility).
 */
export type RagStreamEvent =
    | Vectros.RagStreamEvent.SearchResults
    | Vectros.RagStreamEvent.TruncationWarning
    | Vectros.RagStreamEvent.ContentDelta
    | Vectros.RagStreamEvent.Done
    | Vectros.RagStreamEvent.Error;

export namespace RagStreamEvent {
    export interface SearchResults extends Vectros.SearchResultsEvent {
        type: "search_results";
    }

    export interface TruncationWarning extends Vectros.TruncationWarningEvent {
        type: "truncation_warning";
    }

    export interface ContentDelta extends Vectros.ContentDeltaEvent {
        type: "content_delta";
    }

    export interface Done extends Vectros.DoneEvent {
        type: "done";
    }

    export interface Error extends Vectros.ErrorEvent {
        type: "error";
    }
}
