// This file was auto-generated by Fern from our API Definition.

/**
 * A single result used to ground the answer.
 */
export interface RagSearchResult {
    /** The stable identifier of the matched result (a document or a record). */
    documentId: string;
    /** The combined relevance score from hybrid ranking. Higher is more relevant. */
    score: number;
    /** The keyword (BM25) relevance score, from 0 to 1. Null when this match came from semantic search only. */
    textScore?: number | undefined;
    /** The cosine-similarity score from semantic (vector) search, from 0 to 1. Null when this match came from keyword search only. */
    semanticScore?: number | undefined;
    /** The specific chunk of text that matched the query — the narrowest snippet, useful for citation. */
    chunkText?: string | undefined;
    /** The wider surrounding passage supplied to the model as context — broader than `chunkText` to better ground the answer. */
    contextText?: string | undefined;
    /** A display-ready snippet with the matched query terms emphasized — suitable for search-result UIs. */
    snippet?: string | undefined;
    /** Metadata you supplied on the source document, such as its title, folder id, or custom tags. */
    metadata?: Record<string, unknown> | undefined;
    /** The result's creation timestamp, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
}
