// This file was auto-generated by Fern from our API Definition.

/**
 * A single result used to ground the answer.
 */
export interface RagSearchResult {
    /** The stable identifier of the matched result (a document or a record). */
    documentId: string;
    /** The externalId you supplied for the source item at ingestion, if any. Null when the item was ingested without one, or when it was indexed before this field existed and hasn't been updated or reindexed since. */
    externalId?: string | undefined;
    /** The combined relevance score from hybrid ranking. Higher is more relevant. */
    score: number;
    /** The keyword relevance component of the score. Non-zero in HYBRID mode when the keyword engine contributes to the match, and in TEXT mode. In TEXT mode this is a rank-derived value reflecting the result's relative position, not a normalized BM25 magnitude — meaningful for ordering within this response, not comparable across requests or against HYBRID/SEMANTIC scores. 0 (not null) when this match came from semantic search only. */
    textScore?: number | undefined;
    /** The cosine-similarity score from semantic (vector) search, from 0 to 1. 0 (not null) when this match came from keyword search only. */
    semanticScore?: number | undefined;
    /** The specific chunk of text that matched the query — the narrowest snippet, useful for citation. */
    chunkText?: string | undefined;
    /** The wider surrounding passage supplied to the model as context — broader than `chunkText` to better ground the answer. */
    contextText?: string | undefined;
    /** A display-ready snippet with the matched query terms emphasized — suitable for search-result UIs. */
    snippet?: string | undefined;
    /** Metadata you supplied on the source document, such as its title, folder id, or custom tags. */
    metadata?: Record<string, unknown> | undefined;
    /** The result's creation timestamp, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
}
