// This file was auto-generated by Fern from our API Definition.

/**
 * Per-call read metering
 */
export interface ReadCalls {
    /** Read (GET) calls this period */
    used?: number | undefined;
    /** Included free read calls for your plan this period. Null means unlimited. */
    freeAllowance?: (number | null) | undefined;
    /** Calls beyond the free allowance (billed) */
    overage?: number | undefined;
    /** Credits charged for overage calls (rounded down) */
    overageCredits?: number | undefined;
    /** overageCredits in milli-credit precision (exact) */
    overageCreditsMilli?: number | undefined;
}
