// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A page of PHI read-access (accounting-of-disclosures) rows — a `{data, nextCursor}` envelope. `nextCursor` is an opaque cursor, null when no more pages remain; pass it back as the `startFrom` query param to fetch the next page.
 */
export interface ReadAccessLogPage {
    /** The items on this page, in the endpoint's natural order. Empty when there are no results. */
    data?: Vectros.ReadAccessLogResponse[] | undefined;
    /** An opaque cursor for the next page. Pass it back as the `startFrom` query parameter to continue paging; null when there are no more results. Treat it as opaque — do not parse or construct it. */
    nextCursor?: (string | null) | undefined;
}
