// This file was auto-generated by Fern from our API Definition.

/**
 * One ownership dimension of a disclosed row.
 */
export interface ReadAccessSubject {
    /** The kind of subject: `user` (the principal), or an ownership namespace such as the built-in `org` and `client`, or one you registered such as `team`. A subject kind is your data, not a fixed list. */
    type?: string | undefined;
    /** Identifier of the data subject. */
    id?: string | undefined;
}
