// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Read metering: a per-call axis (GET request infrastructure) and a unified data-out (egress) axis. data-out covers ALL response egress — reads, payload-bearing GETs, search results, and document downloads (the documents.downloads line is the document-only slice of this).
 */
export interface ReadsSection {
    calls?: Vectros.ReadCalls | undefined;
    dataOut?: Vectros.DataOut | undefined;
}
