// This file was auto-generated by Fern from our API Definition.

/**
 * A record: a structured JSON payload that is stored and, optionally, indexed for search.
 */
export interface RecordResponse {
    /** Unique identifier for this record (UUID), assigned by Vectros at creation. */
    id?: string | undefined;
    /** The record's type, matching the `typeName` declared on the schema this record was created against. */
    typeName?: string | undefined;
    /** Identifier of the schema this record was validated against. */
    schemaId?: string | undefined;
    /** The version of the governing schema at the moment this record was written. The schema version increments on every schema edit, but a record keeps the version it was stamped with at write time even after the schema evolves — so you always know which schema shape the payload conforms to. Null for a record created without a schema. */
    schemaVersion?: number | undefined;
    /** Your own stable identifier for this record. Immutable, and unique within your account, context, and record type. Null if the record was created without one. */
    externalId?: string | undefined;
    /** The record's data payload. Its structure is defined by the referenced schema. Fields the schema marks as searchable are indexed for full-text and semantic search. When a record's payload is stored externally (because it is large), list and lookup responses return only the indexed/metadata projection here and set `payloadExternalized` to true; to retrieve the full payload, fetch the record by id (`GET /v1/records/{id}`) or pass `includePayload=true` on the list or lookup call. */
    payload?: Record<string, unknown> | undefined;
    /** True when this record's full payload is stored externally rather than inline. In that case list and lookup responses return only the indexed projection in `payload` unless `includePayload=true` was passed; fetching the record by id always returns the full payload. Null (omitted) for inline records. */
    payloadExternalized?: boolean | undefined;
    /** Size in bytes of the full externalized payload. Present only when `payloadExternalized` is true. */
    payloadBytes?: number | undefined;
    /** Record lifecycle status. ACTIVE records are live. Use this field to model soft-delete or workflow states without physically deleting records. */
    status?: string | undefined;
    /** Identifier of the folder grouping this record. A folder can group both records and documents together. */
    folderId?: string | undefined;
    /** Identifier of the owning user (a Vectros-assigned UUID). Set automatically from the calling token's identity when the token carries a user identity. */
    userId?: string | undefined;
    /** Identifier of the owning organization (a Vectros-assigned UUID). Set automatically from the calling token's identity when the token carries an organization identity. */
    orgId?: string | undefined;
    /** Identifier of the associated client (a Vectros-assigned UUID). Set automatically from the calling token's identity when the token carries a client identity. */
    clientId?: string | undefined;
    /** Search-index status. PENDING_INDEX means the record is queued for indexing. INDEXED means it is searchable via `POST /v1/search`. SKIPPED means the record had no indexable text (e.g. only non-searchable fields populated) so there was nothing to index — it is stored and retrievable, just not full-text/semantic searchable until a searchable field is filled in; not an error. FAILED means indexing hit an error — the record is still readable but not searchable. Null for a store-only record (`indexMode` NONE), which has no indexing to track. */
    indexStatus?: RecordResponse.IndexStatus | undefined;
    /** The record's resolved search-index mode: the per-record override if set, otherwise the schema's type-level default, otherwise NONE. HYBRID, SEMANTIC, and TEXT make the record searchable; NONE is store-only. */
    indexMode?: RecordResponse.IndexMode | undefined;
    /** Identifier of the API key or scoped token that created this record (for example, `key_abc123` for an API key). */
    createdBy?: string | undefined;
    /** When the record was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the record was last updated, as an ISO-8601 UTC timestamp. */
    updatedAt?: string | undefined;
    /** Optimistic-concurrency version. Pass this value back as `expectedVersion` on a later update to avoid silently overwriting a concurrent change — the update is rejected with 409 VERSION_CONFLICT if the record changed in the meantime. Incremented on every successful write. */
    version?: number | undefined;
}

export namespace RecordResponse {
    /** Search-index status. PENDING_INDEX means the record is queued for indexing. INDEXED means it is searchable via `POST /v1/search`. SKIPPED means the record had no indexable text (e.g. only non-searchable fields populated) so there was nothing to index — it is stored and retrievable, just not full-text/semantic searchable until a searchable field is filled in; not an error. FAILED means indexing hit an error — the record is still readable but not searchable. Null for a store-only record (`indexMode` NONE), which has no indexing to track. */
    export const IndexStatus = {
        PendingIndex: "PENDING_INDEX",
        Indexed: "INDEXED",
        Skipped: "SKIPPED",
        Failed: "FAILED",
    } as const;
    export type IndexStatus = (typeof IndexStatus)[keyof typeof IndexStatus];
    /** The record's resolved search-index mode: the per-record override if set, otherwise the schema's type-level default, otherwise NONE. HYBRID, SEMANTIC, and TEXT make the record searchable; NONE is store-only. */
    export const IndexMode = {
        Hybrid: "HYBRID",
        Semantic: "SEMANTIC",
        Text: "TEXT",
        None: "NONE",
    } as const;
    export type IndexMode = (typeof IndexMode)[keyof typeof IndexMode];
}
