// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Record activity breakdown
 */
export interface RecordsSection {
    writes?: Vectros.RecordWrites | undefined;
    primaryStorageBytes?: Vectros.StorageEntry | undefined;
    secondaryStorageBytes?: Vectros.StorageEntry | undefined;
    auditStorageBytes?: Vectros.StorageEntry | undefined;
}
