// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A page of records in a `{data, nextCursor}` envelope: `data` is the array of records on this page, and `nextCursor` is an opaque pagination cursor. Pass it as `startFrom` to fetch the next page; it is null when no more pages remain.
 */
export interface RecordPage {
    /** The items on this page, in the endpoint's natural order. Empty when there are no results. */
    data?: Vectros.RecordResponse[] | undefined;
    /** An opaque cursor for the next page. Pass it back as the `startFrom` query parameter to continue paging; null when there are no more results. **Treat it as opaque** — echo it back unmodified, and never parse, construct, store long-term or compare it. Its format is unspecified, differs between endpoints, and changes between releases. A cursor is valid only for the exact query that returned it: keep every other parameter identical while paging. */
    nextCursor?: (string | null) | undefined;
}
