// This file was auto-generated by Fern from our API Definition.

/**
 * Record write counts and credits
 */
export interface RecordWrites {
    /** Base record writes (one per create/update) */
    count?: number | undefined;
    /** Logical index credits maintained by these writes — ownership + externalId + schema lookup fields (an equality index counts 1, a range-enabled index counts 3). */
    indexCount?: number | undefined;
    /** Credits charged for all record writes this period (rounded down) */
    credits?: number | undefined;
    /** credits in milli-credit precision (exact) */
    creditsMilli?: number | undefined;
}
