// This file was auto-generated by Fern from our API Definition.

/**
 * The token's allowed actions and identity, resolved server-side from the same plaintext scope data baked into the token's own (compressed) `scope` claim. Read this instead of decoding the token client-side.
 */
export interface ResolvedScope {
    /** The union of `allowed_actions` across every clause the token carries. `["*"]` for a wildcard-scoped credential. */
    allowedActions?: string[] | undefined;
    /** The token's `identity` claim — the ownership dimensions (canonical `scope:<namespace>` keys, plus `userId` when the token is bound to a specific user) this credential's own writes stamp by default. Empty for a credential with none (e.g. an unbound owner or service token). */
    identity?: Record<string, string> | undefined;
}
