// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A role: a named, reusable set of scope clauses that can be assigned to users independently of any one identity.
 */
export interface RoleResponse {
    /** The role's globally unique identifier, composed from your account, the app context, and the role ID. Pass this value as the pagination cursor to fetch the next page. */
    id?: string | undefined;
    /** The ID of the app context this role belongs to. */
    contextId?: string | undefined;
    /** Your own identifier for this role within the app context. */
    roleId?: string | undefined;
    /** A human-readable display name for the role. */
    name?: string | undefined;
    /** An optional free-text description of what the role grants. */
    description?: string | undefined;
    /** The role's permissions, expressed as one or more scope clauses. An action is permitted if any clause allows it and that clause's data scope matches the target. */
    scopes?: Vectros.ScopeClause[] | undefined;
    /** When the role was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the role was last modified, as an ISO-8601 UTC timestamp. */
    lastModified?: string | undefined;
}
