// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A page of roles as a `{data, nextCursor}` envelope. `nextCursor` is an opaque cursor — pass it back as `startFrom` to fetch the next page, or null when no more pages remain.
 */
export interface RolePage {
    /** The items on this page, in the endpoint's natural order. Empty when there are no results. */
    data?: Vectros.RoleResponse[] | undefined;
    /** An opaque cursor for the next page. Pass it back as the `startFrom` query parameter to continue paging; null when there are no more results. **Treat it as opaque** — echo it back unmodified, and never parse, construct, store long-term or compare it. Its format is unspecified, differs between endpoints, and changes between releases. A cursor is valid only for the exact query that returned it: keep every other parameter identical while paging. */
    nextCursor?: (string | null) | undefined;
}
