// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * A record schema, defining the structure and behavior of a record type.
 */
export interface SchemaResponse {
    /** Whether this call created a new schema. True when a new schema was created; false when a schema with the same `typeName` already existed and was returned unchanged (idempotent create) or reconciled to the submitted shape (when `?upsert=true`). Present only on the create response (POST /v1/schemas); absent on reads. The HTTP status mirrors it — 201 when created, 200 when an existing schema was returned. */
    created?: boolean | undefined;
    /** Unique identifier for this schema. */
    id?: string | undefined;
    /** Type identifier for this schema. */
    typeName?: string | undefined;
    /** Human-readable display name. */
    displayName?: string | undefined;
    /** Description of what this schema is for. */
    description?: string | undefined;
    /** Field definitions used to validate record payloads. */
    fields?: Vectros.FieldDef[] | undefined;
    /** Payload fields indexed for direct lookup queries. */
    lookupFields?: Vectros.LookupDef[] | undefined;
    /** UI rendering hints keyed by field id. */
    renderHints?: Record<string, Vectros.RenderHintDef> | undefined;
    /** Feature flags for this schema. `auditHistory` (default true) controls whether a change-history (version) trail is kept for this type's data; it never affects the records themselves. `readAccessLog` (default false) controls accounting-of-disclosures logging for reads of this type's records. */
    capabilities?: Record<string, boolean> | undefined;
    /** Payload storage profile: STANDARD (externalize large payloads to S3), LOW_LATENCY (always store inline), or LARGE_PAYLOAD (always externalize). Defaults to STANDARD. */
    storageProfile?: SchemaResponse.StorageProfile | undefined;
    /** Default search-index mode for this type's records: HYBRID, SEMANTIC, TEXT, or NONE (store-only, not searchable). */
    indexMode?: SchemaResponse.IndexMode | undefined;
    /** Which typed surfaces may bind this schema (record, document, user, org, or client). Always present (it is required at write time). */
    allowedSurfaces?: SchemaResponse.AllowedSurfaces.Item[] | undefined;
    /** Whether this schema is active. */
    active?: boolean | undefined;
    /** Schema version number, incremented each time the schema definition changes. */
    schemaVersion?: number | undefined;
    /** When the schema was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the schema was last modified, as an ISO-8601 UTC timestamp. */
    updatedAt?: string | undefined;
}

export namespace SchemaResponse {
    /** Payload storage profile: STANDARD (externalize large payloads to S3), LOW_LATENCY (always store inline), or LARGE_PAYLOAD (always externalize). Defaults to STANDARD. */
    export const StorageProfile = {
        Standard: "STANDARD",
        LowLatency: "LOW_LATENCY",
        LargePayload: "LARGE_PAYLOAD",
    } as const;
    export type StorageProfile = (typeof StorageProfile)[keyof typeof StorageProfile];
    /** Default search-index mode for this type's records: HYBRID, SEMANTIC, TEXT, or NONE (store-only, not searchable). */
    export const IndexMode = {
        Hybrid: "HYBRID",
        Semantic: "SEMANTIC",
        Text: "TEXT",
        None: "NONE",
    } as const;
    export type IndexMode = (typeof IndexMode)[keyof typeof IndexMode];
    export type AllowedSurfaces = AllowedSurfaces.Item[];

    export namespace AllowedSurfaces {
        /** Which typed surfaces may bind this schema (record, document, user, org, or client). Always present (it is required at write time). */
        export const Item = {
            Record: "record",
            Document: "document",
            User: "user",
            Org: "org",
            Client: "client",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
