// This file was auto-generated by Fern from our API Definition.

/**
 * The actions and data a scoped token is allowed to access.
 */
export interface ScopeRequest {
    /** The actions this token may perform. Each entry has the form `resource:operations`, where `operations` is one of `r` (read), `c` (create), `u` (update), `d` (delete), `crud` (all four), or a colon-separated combination. For records you may append a type qualifier, e.g. `records:r:intake_form`. Valid resources are: `clients`, `orgs`, `users`, `documents`, `folders`, `records`, `schemas`, and `search`. */
    allowedActions?: string[] | undefined;
    /** Ownership fields automatically stamped onto resources created with this token. Optional. Keys are ownership fields (`userId`, `orgId`, `clientId`); values must be Vectros entity UUIDs — look them up with `GET /v1/users`, `/v1/orgs`, or `/v1/clients`. The token holder cannot override these values when creating resources. */
    identity?: Record<string, string> | undefined;
    /** Restricts which records the token can access. Optional. Keys are ownership fields (`userId`, `orgId`, `clientId`); values are arrays of permitted entity UUIDs — the token can only access records whose ownership field matches one of these values. Every non-null UUID must be a real entity in your account. Include a JSON `null` in the array (e.g. `["uuid", null]`) to ALSO grant access to records whose ownership field is unset — this is the explicit "records with no assigned org, client, or user" sentinel, NOT a wildcard. To grant access regardless of value, omit the key from the data scope entirely. */
    dataScope?: Record<string, string[]> | undefined;
}
