// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata for a scoped API key (`ssk_*`).
 */
export interface ScopedKeyResponse {
    /** Server-generated identifier for the key, stable for its entire lifetime. Pass this in the URL path of the get and revoke endpoints. */
    keyId?: string | undefined;
    /** The raw secret key. Returned ONLY in the response to creating the key; all subsequent reads omit this field. Treat it as a sensitive credential and store it securely. */
    rawKey?: string | undefined;
    /** The human-readable name you gave the key when creating it. */
    keyName?: string | undefined;
    /** Optional display label for the key, surfaced through `/v1/ping` as `principalLabel`. Omitted when no label was set. */
    label?: string | undefined;
    /** The tenant the key operates on — either your live or your test environment. */
    tenantId?: string | undefined;
    /** The app context the key is bound to. */
    contextId?: string | undefined;
    /** The user the key acts as. This is the same user ID used by the `/v1/users` endpoints. */
    userId?: string | undefined;
    /** The bound user's type: `HUMAN` or `SERVICE`. Included as a convenience for filtering in admin interfaces. */
    userType?: ScopedKeyResponse.UserType | undefined;
    /** The key's lifecycle status: `active` or `revoked`. */
    status?: ScopedKeyResponse.Status | undefined;
    /** Always `scoped` for keys created through this endpoint. The field exists so this response shape can also represent unscoped (`sk_*`) keys. */
    keyType?: ScopedKeyResponse.KeyType | undefined;
    /** Reference to the bound access profile, in the form `tenant#context#usr_user` (the user segment carries the `usr_` prefix). Useful for cross-referencing the profile via `/v1/app-contexts/{contextId}/profiles/{principalId}`. */
    accessProfileRef?: string | undefined;
    /** When the key was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
    /** When the key was revoked, as an ISO-8601 UTC timestamp. Present only on revoked keys. */
    revokedAt?: string | undefined;
    /** When the key was most recently used, as an ISO-8601 UTC timestamp. This value is coarse (updated at most about once an hour) and best-effort. Null if the key has not been used since usage tracking began. */
    lastUsedAt?: string | undefined;
}

export namespace ScopedKeyResponse {
    /** The bound user's type: `HUMAN` or `SERVICE`. Included as a convenience for filtering in admin interfaces. */
    export const UserType = {
        Human: "HUMAN",
        Service: "SERVICE",
    } as const;
    export type UserType = (typeof UserType)[keyof typeof UserType];
    /** The key's lifecycle status: `active` or `revoked`. */
    export const Status = {
        Active: "active",
        Revoked: "revoked",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Always `scoped` for keys created through this endpoint. The field exists so this response shape can also represent unscoped (`sk_*`) keys. */
    export const KeyType = {
        Scoped: "scoped",
    } as const;
    export type KeyType = (typeof KeyType)[keyof typeof KeyType];
}
