// This file was auto-generated by Fern from our API Definition.

/**
 * A reference to a stored script by name and version — the script a trigger rule invokes, or the one `POST /v1/scripts/execute` runs.
 */
export interface ScriptRefRequest {
    /** The referenceable script name (see POST /v1/scripts). */
    name: string;
    /** A specific version number (as a decimal string), or the literal 'latest' to float to whichever version is newest when the rule fires or the request runs. */
    version: string;
}
