// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for pushing a new script object version. Scripts are immutable per version — there is no update surface; push a new version with another POST.
 */
export interface ScriptRequest {
    /** The script's referenceable name/slug — stable across versions. Must be 1-64 characters of letters, digits, underscores ('_'), and hyphens ('-'). Required. */
    name: string;
    /** The script's source text, stored as-is: nothing parses or validates it at push time, so a syntax error surfaces as a `SCRIPT_ERROR` when the version first runs — from a trigger rule that references it, or from `POST /v1/scripts/execute`. Required, non-blank. Capped at 300,000 UTF-8 bytes (~300 KB) — an oversized push is rejected with a 400. */
    source: string;
    /** Optional free-text description of the input shape this script expects. Not validated or enforced in this release. Capped at 50,000 UTF-8 bytes (~50 KB) — an oversized value is rejected with a 400. */
    declaredInputContract?: string | undefined;
}
