// This file was auto-generated by Fern from our API Definition.

/**
 * A single content chunk that matched the search query.
 */
export interface SearchResult {
    /** The ID of the source document or record this chunk belongs to. Use it with `GET /v1/documents/{id}` or `GET /v1/records/{id}` (depending on `sourceType`) to retrieve the full item. */
    documentId?: string | undefined;
    /** The `externalId` you supplied for the source item at ingestion, if any. Null when the item was ingested without one, or when the source item was indexed before this field existed and hasn't been updated or reindexed since. */
    externalId?: string | undefined;
    /** The combined relevance score that fuses the text and semantic signals (reciprocal rank fusion). This is the primary sort key — a higher value means a more relevant result. */
    score?: number | undefined;
    /** The keyword (BM25) relevance component of the score. Non-zero in HYBRID mode when the keyword engine contributes to the match. In TEXT mode this is a rank-derived value reflecting the result's relative position, not a raw BM25 magnitude — treat it as meaningful for ordering within this response, not as a score comparable across requests or against other modes. */
    textScore?: number | undefined;
    /** The semantic (vector similarity) component of the score. Non-zero when the search mode is SEMANTIC or HYBRID. */
    semanticScore?: number | undefined;
    /** The exact text chunk that matched the query. Pass this to your model as the retrieved context. */
    chunkText?: string | undefined;
    /** A broader passage surrounding the matched chunk. Use this instead of `chunkText` when you need more context — for example to avoid fragmentation when building a long-context prompt for a model. */
    contextText?: string | undefined;
    /** A short excerpt with the matched query terms highlighted. Suitable for display in a search results UI. */
    snippet?: string | undefined;
    /** Indicates what kind of source item this result came from: `PartnerDocument` for documents ingested via `POST /v1/documents` or `POST /v1/documents/upload`, and `GenericRecord` for typed records created via `POST /v1/records`. Use this to branch when rendering a mix of documents and records from a unified search. */
    sourceType?: SearchResult.SourceType | undefined;
    /** The metadata you supplied for this item when you ingested it, such as its title, folder ID, and any custom fields you included. */
    metadata?: Record<string, unknown> | undefined;
    /** When the source item was created, as an ISO-8601 UTC timestamp. */
    createdAt?: string | undefined;
}

export namespace SearchResult {
    /** Indicates what kind of source item this result came from: `PartnerDocument` for documents ingested via `POST /v1/documents` or `POST /v1/documents/upload`, and `GenericRecord` for typed records created via `POST /v1/records`. Use this to branch when rendering a mix of documents and records from a unified search. */
    export const SourceType = {
        PartnerDocument: "PartnerDocument",
        GenericRecord: "GenericRecord",
    } as const;
    export type SourceType = (typeof SourceType)[keyof typeof SourceType];
}
