// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * The result of a search: the matched content chunks plus metadata about the search run.
 */
export interface SearchResponse {
    /** The matched content chunks, ordered from most to least relevant. */
    results?: Vectros.SearchResult[] | undefined;
    /** The total number of items that matched the query (the size of the matching pool). This may be larger than the number of results returned in this response, which is capped by `limit`. */
    totalResults?: number | undefined;
    /** How long the search took to run, in milliseconds. */
    searchTimeMs?: number | undefined;
    /** True when one of the two search engines was unavailable and these results came from the surviving engine only (for example, keyword search fell back to semantic-only during an outage). When true, the results may be less complete than a healthy hybrid search. Set `requireComplete` to true on your request to receive a 503 instead of partial results. */
    degraded?: boolean | undefined;
    /** Which search engines were unavailable for this response: `text` (keyword) and/or `vector` (semantic). Empty when the search was not degraded. */
    degradedLegs?: string[] | undefined;
}
