// This file was auto-generated by Fern from our API Definition.

/**
 * Safe field — updatable. Omit to leave unchanged; pass an empty list to disable self-signup entirely. See `IssuerRequest.selfSignupPolicies` for the full semantics — the same elevated-role restriction applies here.
 */
export interface SelfSignupPolicy {
    /** The plain slug the frontend and the blueprint agree on to select this policy entry (e.g. 'practitioner', 'client'). Same grammar as a role id (lowercase letter first, then a-z 0-9 -, 3-31 chars). Caller-supplied at exchange time via the request's signup_type field; omitted on the request means 'the sole entry', valid only when this list has exactly one. */
    signup_type: string;
    /** The role a brand-new self-signup caller matching this signupType is bound to. Must never resolve to a role carrying elevated (provisioning or wildcard) scope — checked when you register this policy (skipped if the role doesn't exist yet) and always checked again, unskippable, at the moment a caller actually signs up. */
    role_id: string;
}
