// This file was auto-generated by Fern from our API Definition.

/**
 * Configured self-service signup policies, if any. Absent (not an empty list) when self-signup is not configured for this issuer.
 */
export interface SelfSignupPolicy {
    /** The plain slug the frontend and the blueprint agree on to select this policy entry (e.g. 'practitioner', 'client'). Same grammar as a role id (lowercase letter first, then a-z 0-9 -, 3-31 chars). Caller-supplied at exchange time via the request's signup_type field; omitted on the request means 'the sole entry', valid only when this list has exactly one. */
    signup_type: string;
    /** The role a brand-new self-signup caller matching this signupType is bound to. Must never resolve to a role carrying elevated (provisioning or wildcard) scope — checked when you register this policy (skipped if the role doesn't exist yet) and always checked again, unskippable, at the moment a caller actually signs up. */
    role_id: string;
}
