// This file was auto-generated by Fern from our API Definition.

/**
 * Storage bytes with estimated monthly credit cost
 */
export interface StorageEntry {
    /** Bytes stored */
    bytes?: number | undefined;
    /** Estimated credits this period for this storage (final billing at cycle end) */
    estimatedCredits?: number | undefined;
    /** estimatedCredits in milli-credit precision (exact). Storage credits are computed in whole-credit units today (HUNDRED_MB granularity), so this currently equals estimatedCredits * 1000 — the field is exposed for future-proofing when sub-credit storage rates land. */
    estimatedCreditsMilli?: number | undefined;
}
