// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../index.js";

/**
 * Full usage breakdown for a single environment
 */
export interface TenantDetail {
    /** Environment id — your account (tenant) id for this environment, as a UUID. Null if the environment doesn't exist (rare). */
    id?: (string | null) | undefined;
    credits?: Vectros.TenantCredits | undefined;
    search?: Vectros.SearchSection | undefined;
    documents?: Vectros.DocumentsSection | undefined;
    records?: Vectros.RecordsSection | undefined;
    inference?: Vectros.TenantInferenceSection | undefined;
}
