// This file was auto-generated by Fern from our API Definition.

/**
 * Environment-scoped credit total (no limit/breakdown — those live at the account level)
 */
export interface TenantCredits {
    /** Credits consumed by this environment this period (rounded down) */
    used?: number | undefined;
    /** used in milli-credit precision (exact, 1 credit = 1000 milli-credits). Use this for exact accounting — `tenants.live.credits.used + tenants.test.credits.used` can differ from the account-level `credits.used` by up to 1 credit due to independent truncation, but `live.usedMilli + test.usedMilli == credits.usedMilli` always. */
    usedMilli?: number | undefined;
}
