// This file was auto-generated by Fern from our API Definition.

/**
 * POST /v1/auth/token/assume success response.
 */
export interface TokenAssumeResponse {
    /** The re-minted Vectros scoped token — every claim identical to the presented token except `identity.<namespace>`, including `exp` (see `expires_in`). */
    access_token?: string | undefined;
    /** Always `Bearer`. */
    token_type?: string | undefined;
    /** Seconds until expiry. ALWAYS the presented token's own remaining lifetime — assuming a namespace value never resets or extends it. */
    expires_in?: number | undefined;
}
