// This file was auto-generated by Fern from our API Definition.

/**
 * The deletion fact for a hard-deleted record. Returned by GET /v1/records/{id}/tombstone.
 */
export interface TombstoneResponse {
    /** The original Vectros-assigned UUID of the now-deleted record. */
    id?: string | undefined;
    /** The record type the deleted record belonged to. */
    recordType?: string | undefined;
    /** Identifier of the user or API key that deleted the record. */
    deletedBy?: string | undefined;
    /** The id of the DELETE entry in the record's version history (GET /v1/records/{id}/versions), if that history is still reachable. */
    deleteVersionId?: string | undefined;
    /** A short, system-generated description of why the record was deleted. */
    deletionReason?: string | undefined;
    /** Time the record was deleted, as an ISO-8601 UTC timestamp. */
    deletedAt?: string | undefined;
}
