// This file was auto-generated by Fern from our API Definition.

/**
 * Emitted by `POST /v1/rag` when one or more retrieved results were dropped before the prompt was built, for either (or both) of two independent reasons: the results didn't fit the model's context window (`truncatedCount`), or a result had no groundable text to include at all (`noContentCount`) — so the answer is grounded on fewer results than were retrieved.
 */
export interface TruncationWarningEvent {
    /** Backward-compatible alias of `type`. Always `truncation_warning`. */
    event: TruncationWarningEvent.Event;
    /** The number of results retrieved before any were dropped. */
    resultsRequested: number;
    /** The number of results actually included in the prompt — `resultsRequested` minus `truncatedCount` minus `noContentCount`. */
    resultsUsed: number;
    /** How many of the dropped results were cut for context-window budget reasons (lower-scoring overflow). 0 if none were. */
    truncatedCount: number;
    /** How many of the dropped results had no groundable text to include at all, independent of budget. 0 if none were. */
    noContentCount: number;
    /** A single human-readable summary of why results were dropped: `context_window_budget` (only the budget reason applied), `no_groundable_content` (only the no-content reason applied), or `context_window_budget_and_no_content` (both applied). A caller wanting exact attribution should read `truncatedCount`/`noContentCount` directly rather than parse this field. */
    reason: TruncationWarningEvent.Reason;
}

export namespace TruncationWarningEvent {
    /** Backward-compatible alias of `type`. Always `truncation_warning`. */
    export const Event = {
        TruncationWarning: "truncation_warning",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
    /** A single human-readable summary of why results were dropped: `context_window_budget` (only the budget reason applied), `no_groundable_content` (only the no-content reason applied), or `context_window_budget_and_no_content` (both applied). A caller wanting exact attribution should read `truncatedCount`/`noContentCount` directly rather than parse this field. */
    export const Reason = {
        ContextWindowBudget: "context_window_budget",
        NoGroundableContent: "no_groundable_content",
        ContextWindowBudgetAndNoContent: "context_window_budget_and_no_content",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
