// This file was auto-generated by Fern from our API Definition.

/**
 * Write counts and credits for a schema-driven surface (documents / identity). Same shape as record writes: a base count plus the extra schema-lookup-field writes, with the combined credits.
 */
export interface WriteStats {
    /** Base writes (one per create/update) */
    count?: number | undefined;
    /** Logical index credits maintained by these writes — ownership + externalId + schema lookup fields (an equality index counts 1, a range-enabled index counts 3). */
    indexCount?: number | undefined;
    /** Credits charged for all writes on this surface this period (rounded down) */
    credits?: number | undefined;
    /** credits in milli-credit precision (exact) */
    creditsMilli?: number | undefined;
}
