// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         messages: [{
 *                 role: "system",
 *                 content: "content"
 *             }]
 *     }
 */
export interface ChatRequest {
    /** The conversation history, in order. A message with role `system` is extracted and used as the system prompt; `user` and `assistant` messages are sent to the model as conversation turns. */
    messages: Vectros.ChatMessage[];
    /** Model alias to use, from the list returned by `GET /v1/models`. Defaults to `claude-haiku-4-5`. */
    model?: string;
    /** Maximum number of tokens to generate. Defaults to 2048; the maximum is 8192. */
    maxTokens?: number;
    /** Sampling temperature, between 0.0 and 1.0. Higher values produce more varied output. Defaults to 0.7. */
    temperature?: number;
    /** Top-p (nucleus) sampling. Ignored when `temperature` is greater than 0. */
    topP?: number;
    /** Opt this request into global (non-US) region serving for lower cost. Requires a signed global-processing waiver on your account that permits per-request override; otherwise the request is rejected with 403. When omitted, the request follows your account's default residency setting. Configure data residency under Data Residency and Region settings in the developer portal. */
    allowGlobalRegion?: boolean;
}
