// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface RagRequest {
    /** The natural-language question to answer over your indexed content. Combined with `instructions`, must not exceed roughly 8,000 tokens (~32K characters) — this field is a question, not a place for bulk context; large context belongs in your indexed content, retrieved via search. */
    query: string;
    /** Optional system prompt that overrides the default. Defaults to a generic instruction to answer using only the provided context. Combined with `query`, must not exceed roughly 8,000 tokens (~32K characters). */
    instructions?: string;
    /** Model alias to use, from the list returned by `GET /v1/models`. Defaults to `claude-haiku-4-5`. When `providerAlias` is set, this instead names the MODEL on that BYO provider's own id space (opaque to Vectros) — falls back to the provider config's own default model when omitted. */
    model?: string;
    search?: Vectros.RagSearch;
    /** Maximum number of tokens to generate. Defaults to 1024; the maximum is 4096. */
    maxTokens?: number;
    /** Sampling temperature. Defaults to 0.3, favoring more deterministic, retrieval-grounded answers. */
    temperature?: number;
    /** Opt this request into global (non-US) region serving for lower cost. Requires a signed global-processing waiver on your account that permits per-request override; otherwise the request is rejected with 403. When omitted, the request follows your account's default residency setting. */
    allowGlobalRegion?: boolean;
    /** Route this request through a BYO (bring-your-own) model provider config instead of platform-hosted Bedrock — the alias of a provider config your account has activated (a customer-supplied Anthropic key or OpenAI-compatible endpoint). Requires the corresponding risk waiver on your account; otherwise, or if the alias is unknown or inactive, the request is rejected with 403. The request is sent to the endpoint on that config: `allowGlobalRegion` and your residency settings do not apply, and the provider determines where it is processed. If neither `model` nor the config's default model is set, the request is rejected with 400. When omitted, the request is served by platform-hosted Bedrock — this field is entirely additive. */
    providerAlias?: string;
}
