// This file was auto-generated by Fern from our API Definition.

export const ListOrgsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListOrgsRequestOrder = (typeof ListOrgsRequestOrder)[keyof typeof ListOrgsRequestOrder];
