// This file was auto-generated by Fern from our API Definition.

export const ListClientsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListClientsRequestOrder = (typeof ListClientsRequestOrder)[keyof typeof ListClientsRequestOrder];
