// This file was auto-generated by Fern from our API Definition.

export const ListEntitiesRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListEntitiesRequestOrder = (typeof ListEntitiesRequestOrder)[keyof typeof ListEntitiesRequestOrder];
