// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "patient intake form diabetes"
 *     }
 */
export interface SearchRequest {
    /** The search query, expressed in natural language or as keywords. Required. */
    query: string;
    /** How results are ranked. HYBRID combines semantic and keyword ranking (recommended). SEMANTIC ranks by vector similarity only. TEXT ranks by keyword matching only. Defaults to HYBRID. */
    mode?: SearchRequest.Mode;
    /** The maximum number of results to return. Must be between 1 and 100. Defaults to 20. */
    limit?: number;
    /** The number of results to skip, for pagination. Must be between 0 and 200. Defaults to 0. */
    offset?: number;
    /** Restrict results to content owned by this user — the Vectros-assigned UUID of a user in your account. Use `GET /v1/users?externalId=` to look up a user's ID from your own identifier. */
    userId?: string;
    /** Restrict results to content belonging to this organization — the Vectros-assigned UUID of an organization in your account. Use `GET /v1/orgs?externalId=` to look up an organization's ID from your own identifier. */
    orgId?: string;
    /** Restrict results to content associated with this client — the Vectros-assigned UUID of a client in your account. Use `GET /v1/clients?externalId=` to look up a client's ID from your own identifier. */
    clientId?: string;
    /** Field-level filters applied to your document and record metadata. Each key is a field name, and top-level keys are AND-combined. Each value is one of: a scalar (string, number, or boolean) for an exact match; an array of scalars to match any one of them; or an operator map for ranges, negation, and membership. The supported operators are a closed set: `$eq`, `$ne`, `$gt`, `$gte`, `$lt`, `$lte` (each takes a scalar) and `$in`, `$nin` (each takes an array of scalars). Operators within one map are AND-combined, so `{"price":{"$gte":100,"$lte":500}}` expresses a closed range; `$in` and `$nin` may not be combined with other operators. Numbers and booleans are matched by type, so the field must have been ingested under a typed schema; dates may be sent as ISO 8601 strings or epoch milliseconds. Unknown operators, non-scalar operands, and malformed field names are rejected with a 400. */
    filters?: Record<string, Vectros.FilterValue>;
    /** How query terms are matched by the keyword engine when the mode is TEXT or HYBRID. OR matches content containing any query term (broadest recall). AND requires every term to be present (higher precision). PHRASE requires the terms to appear as a contiguous sequence. COMPLEX enables the full query syntax, including boolean operators, field-scoped queries, and range filters. When omitted, defaults to PHRASE (with a slop of 3) in HYBRID mode and OR in TEXT mode. */
    textMode?: SearchRequest.TextMode;
    /** The minimum semantic similarity score a result must have to be included, on a scale of 0.0 to 1.0. Results scoring below this threshold are dropped. Applies when the mode is SEMANTIC or HYBRID. */
    minSimilarity?: number;
    /** A relative relevance floor for the keyword leg, given as a fraction from 0 to 1 of the TOP result's score — results scoring below (top score × this value) are dropped. Keyword scores are unbounded and depend on the query, so this is a relative cutoff rather than an absolute score: for example, 0.5 keeps only results at least half as relevant as the best hit. Applies when the mode is TEXT or HYBRID. Omit it (or use a value of 0 or less) to keep all keyword matches. */
    minTextRelevance?: number;
    /** The phrase-match slop: the number of intervening positions allowed between query terms when `textMode` is PHRASE (0 means the terms must be exactly adjacent). Ignored for the other text modes. */
    slop?: number;
    /** When true, returns at most one chunk per source item, so a single document or record cannot appear more than once in the results. */
    uniqueDocuments?: boolean;
    /** Narrow results to specific content types. When omitted, empty, or set to both values, the search returns all content (documents and records) in a single unified result set, which is the default behavior. Each returned result carries a `sourceType` discriminator so you can tell documents and records apart. Pass `["documents"]` for documents only, or `["records"]` for records only. */
    contentTypes?: SearchRequest.ContentTypes.Item[];
    /** Restrict results to content (documents or records) in this EXACT folder. Folders hold a mix of documents and records. Provide the Vectros-assigned UUID of a folder; use `GET /v1/folders` to list your folders. To match a folder AND all of its descendants, use `rootFolderId` instead. */
    folderId?: string;
    /** Restrict results to content (documents or records) anywhere under this folder subtree — the folder itself and all of its descendants. Provide the Vectros-assigned UUID of a top-level (root) folder. Applies to documents and records alike. Use `folderId` instead to match a single exact folder. */
    rootFolderId?: string;
    /** Restrict results to records of a specific schema type (for example `patient` or `intake_form`). Has no effect on documents — it only narrows record results. Setting it implicitly limits the results to records, unless you also include documents via `contentTypes`. */
    typeName?: string;
    /** Restrict results to content created at or after this ISO-8601 UTC timestamp. Useful for incremental queries (for example, finding anything ingested in the last hour), for isolating just-created content from older history, and for time-bounded analytics. Pair it with `createdBefore` to define a window. */
    createdAfter?: string;
    /** Restrict results to content created at or before this ISO-8601 UTC timestamp. Pair it with `createdAfter` to define a window, or use it alone to find content older than a cutoff (for example, in archival or cleanup workflows). */
    createdBefore?: string;
    /** A fail-closed override. When true, the request returns HTTP 503 instead of partial results if one of the search engines is unavailable. Defaults to false, in which case an outage degrades to the surviving engine and the response carries `degraded: true` along with the failed engines in `degradedLegs`. Set this to true only when complete results are required and a degraded answer is unacceptable. */
    requireComplete?: boolean;
}

export namespace SearchRequest {
    /** How results are ranked. HYBRID combines semantic and keyword ranking (recommended). SEMANTIC ranks by vector similarity only. TEXT ranks by keyword matching only. Defaults to HYBRID. */
    export const Mode = {
        Hybrid: "HYBRID",
        Semantic: "SEMANTIC",
        Text: "TEXT",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** How query terms are matched by the keyword engine when the mode is TEXT or HYBRID. OR matches content containing any query term (broadest recall). AND requires every term to be present (higher precision). PHRASE requires the terms to appear as a contiguous sequence. COMPLEX enables the full query syntax, including boolean operators, field-scoped queries, and range filters. When omitted, defaults to PHRASE (with a slop of 3) in HYBRID mode and OR in TEXT mode. */
    export const TextMode = {
        Or: "OR",
        And: "AND",
        Phrase: "PHRASE",
        Complex: "COMPLEX",
    } as const;
    export type TextMode = (typeof TextMode)[keyof typeof TextMode];
    export type ContentTypes = ContentTypes.Item[];

    export namespace ContentTypes {
        /** Narrow results to specific content types. When omitted, empty, or set to both values, the search returns all content (documents and records) in a single unified result set, which is the default behavior. Each returned result carries a `sourceType` discriminator so you can tell documents and records apart. Pass `["documents"]` for documents only, or `["records"]` for records only. */
        export const Item = {
            Documents: "documents",
            Records: "records",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
