// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             typeName: "intake_form",
 *             schemaId: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
 *             payload: {
 *                 "first_name": "Jane",
 *                 "email": "jane@example.com"
 *             },
 *             folderId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
 *         }
 *     }
 */
export interface CreateRecordRequest {
    /** When `true`, if a record with the same `externalId` already exists its content is overwritten (the submitted `payload` and mutable fields are applied and the version is bumped) instead of being returned unchanged; the immutable `externalId`, `schemaId`/`typeName`, and ownership are never changed. A re-applied upsert whose content matches is a no-op (no version bump). Defaults to `false`. Requires the `records:u:<type>` scope in addition to `records:c:<type>`. */
    upsert?: boolean;
    body: Vectros.RecordRequest;
}
