// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "550e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface DeleteRecordRequest {
    /** The Vectros-assigned UUID of the record to delete. */
    id: string;
}
