// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Vectros from "../../../index.js";

export declare namespace SchemasClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Define record types with field validation and lookup indexes
 */
export class SchemasClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SchemasClient.Options>;

    constructor(options: SchemasClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of the record schemas defined in your account. Filter by `userId` or `orgId` to scope to an owner, by `surface` to list the types bindable to one surface, or by `recordType` to resolve the single schema for a type directly. Filtering by an identity surface (user, org, or client) lists your account-wide identity schemas regardless of the calling context; filtering by record or document lists within the calling context. Requires the `schemas:r` scope.
     *
     * @param {Vectros.ListSchemasRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.schemas.listSchemas({
     *         userId: "550e8400-e29b-41d4-a716-446655440000",
     *         orgId: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
     *         surface: "document",
     *         recordType: "intake_form",
     *         startFrom: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
     *     })
     */
    public listSchemas(
        request: Vectros.ListSchemasRequest = {},
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.SchemaPage> {
        return core.HttpResponsePromise.fromPromise(this.__listSchemas(request, requestOptions));
    }

    private async __listSchemas(
        request: Vectros.ListSchemasRequest = {},
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.SchemaPage>> {
        const { userId, orgId, surface, recordType, startFrom, limit } = request;
        const _queryParams: Record<string, unknown> = {
            userId,
            orgId,
            surface,
            recordType,
            startFrom,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/schemas",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.SchemaPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VectrosError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/schemas");
    }

    /**
     * Defines a new record type with optional field definitions, validation rules, and lookup indexes. Idempotent by `typeName` within the same ownership scope: re-creating an existing `typeName` returns the existing schema rather than failing. Requires the `schemas:w` scope.
     *
     * @param {Vectros.SchemaRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     *
     * @example
     *     await client.schemas.createSchema({
     *         typeName: "intake_form",
     *         displayName: "Client Intake Form",
     *         description: "Captures initial client information",
     *         fields: [{
     *                 fieldId: "first_name",
     *                 fieldType: "string",
     *                 required: true,
     *                 searchable: true
     *             }, {
     *                 fieldId: "email",
     *                 fieldType: "string",
     *                 required: true
     *             }],
     *         lookupFields: [{
     *                 fieldName: "email",
     *                 unique: true
     *             }],
     *         capabilities: {
     *             "auditHistory": true
     *         },
     *         allowedSurfaces: ["record"]
     *     })
     */
    public createSchema(
        request: Vectros.SchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.SchemaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSchema(request, requestOptions));
    }

    private async __createSchema(
        request: Vectros.SchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.SchemaResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/schemas",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.SchemaResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/schemas");
    }

    /**
     * Retrieves a single record schema by its id. Requires the `schemas:r` scope.
     *
     * @param {Vectros.GetSchemaRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.schemas.getSchema({
     *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
     *     })
     */
    public getSchema(
        request: Vectros.GetSchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.SchemaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSchema(request, requestOptions));
    }

    private async __getSchema(
        request: Vectros.GetSchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.SchemaResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/schemas/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.SchemaResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/schemas/{id}");
    }

    /**
     * Updates a record schema. Fields you omit are preserved; `typeName` is immutable and cannot be changed. Collection fields (`fields`, `lookupFields`, `renderHints`, `capabilities`) are replaced in full when supplied. Requires the `schemas:w` scope.
     *
     * @param {Vectros.UpdateSchemaRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.schemas.updateSchema({
     *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
     *         body: {
     *             typeName: "intake_form",
     *             displayName: "Client Intake Form",
     *             allowedSurfaces: ["record"]
     *         }
     *     })
     */
    public updateSchema(
        request: Vectros.UpdateSchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.SchemaResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateSchema(request, requestOptions));
    }

    private async __updateSchema(
        request: Vectros.UpdateSchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.SchemaResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/schemas/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.SchemaResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/schemas/{id}");
    }

    /**
     * Permanently deletes a record schema. The request is refused with 409 if records of this type still exist — delete those records first, since every record must reference a live schema. Requires the `schemas:w` scope.
     *
     * @param {Vectros.DeleteSchemaRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.ConflictError}
     *
     * @example
     *     await client.schemas.deleteSchema({
     *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
     *     })
     */
    public deleteSchema(
        request: Vectros.DeleteSchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSchema(request, requestOptions));
    }

    private async __deleteSchema(
        request: Vectros.DeleteSchemaRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/schemas/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Vectros.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/schemas/{id}");
    }

    /**
     * Returns the audit trail of changes to a record schema, newest first (create, update, and delete). Schema version history is always recorded — there is no per-schema toggle to disable it. Requires the `schemas:r` scope.
     *
     * @param {Vectros.GetSchemaVersionsRequest} request
     * @param {SchemasClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.schemas.getSchemaVersions({
     *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
     *     })
     */
    public getSchemaVersions(
        request: Vectros.GetSchemaVersionsRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ModelDataVersionPage> {
        return core.HttpResponsePromise.fromPromise(this.__getSchemaVersions(request, requestOptions));
    }

    private async __getSchemaVersions(
        request: Vectros.GetSchemaVersionsRequest,
        requestOptions?: SchemasClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ModelDataVersionPage>> {
        const { id, startFrom } = request;
        const _queryParams: Record<string, unknown> = {
            startFrom,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/schemas/${core.url.encodePathParam(id)}/versions`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ModelDataVersionPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/schemas/{id}/versions");
    }
}
