// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Vectros from "../../../index.js";

export declare namespace IdentityClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage users, organizations, and clients
 */
export class IdentityClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<IdentityClient.Options>;

    constructor(options: IdentityClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of clients in your account. Narrow the results with `orgId` or `userId`, or use `externalId` for an exact lookup by your own identifier. For schema-bound clients, you can also query by a schema-declared lookup field using `type`, `field`, and one lookup mode (`value` for equality, `from`/`to` for a range, or `prefix`). The response is a `{data, nextCursor}` envelope; pass `nextCursor` back as `startFrom` to fetch the next page. Requires the `clients:r` scope.
     *
     * @param {Vectros.ListClientsRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.identity.listClients({
     *         orgId: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
     *         userId: "550e8400-e29b-41d4-a716-446655440000",
     *         externalId: "patient_789",
     *         startFrom: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
     *         type: "client_v1",
     *         field: "industry",
     *         value: "healthcare",
     *         prefix: "health"
     *     })
     */
    public listClients(
        request: Vectros.ListClientsRequest = {},
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ClientPage> {
        return core.HttpResponsePromise.fromPromise(this.__listClients(request, requestOptions));
    }

    private async __listClients(
        request: Vectros.ListClientsRequest = {},
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ClientPage>> {
        const {
            orgId,
            userId,
            externalId,
            startFrom,
            limit,
            type: type_,
            field,
            value,
            from: from_,
            to,
            prefix,
            order,
        } = request;
        const _queryParams: Record<string, unknown> = {
            orgId,
            userId,
            externalId,
            startFrom,
            limit,
            type: type_,
            field,
            value,
            from: from_,
            to,
            prefix,
            order: order != null ? order : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/clients",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ClientPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VectrosError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/clients");
    }

    /**
     * Creates a new client identity in your account. This call is idempotent on `externalId`: if a client with the same `externalId` already exists, the existing record is returned instead of creating a duplicate. Requires the `clients:c` scope.
     *
     * @param {Vectros.ClientRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.createClient({
     *         externalId: "patient_789"
     *     })
     */
    public createClient(
        request: Vectros.ClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ClientResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createClient(request, requestOptions));
    }

    private async __createClient(
        request: Vectros.ClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ClientResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/clients",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ClientResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/clients");
    }

    /**
     * Returns a single client by its Vectros-assigned UUID. Requires the `clients:r` scope.
     *
     * @param {Vectros.GetClientRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.identity.getClient({
     *         id: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
     *     })
     */
    public getClient(
        request: Vectros.GetClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ClientResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getClient(request, requestOptions));
    }

    private async __getClient(
        request: Vectros.GetClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ClientResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/clients/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ClientResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/clients/{id}");
    }

    /**
     * Updates mutable fields on an existing client. Omitted fields are preserved (a null does not clear a field); when `payload` is supplied it replaces the stored payload in full rather than being deep-merged. Requires the `clients:u` scope.
     *
     * @param {Vectros.UpdateClientRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.updateClient({
     *         id: "id",
     *         body: {
     *             externalId: "patient_789"
     *         }
     *     })
     */
    public updateClient(
        request: Vectros.UpdateClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ClientResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateClient(request, requestOptions));
    }

    private async __updateClient(
        request: Vectros.UpdateClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ClientResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/clients/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ClientResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/clients/{id}");
    }

    /**
     * Permanently deletes the client. This action cannot be undone. Requires the `clients:d` scope.
     *
     * @param {Vectros.DeleteClientRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.deleteClient({
     *         id: "id"
     *     })
     */
    public deleteClient(
        request: Vectros.DeleteClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteClient(request, requestOptions));
    }

    private async __deleteClient(
        request: Vectros.DeleteClientRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/clients/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/clients/{id}");
    }

    /**
     * Body-based equivalent of the `type`/`field`/`value` lookup on `GET /v1/clients`. Use this when looking up by a sensitive (blind-indexed) field: the value travels in the request body rather than the URL. The `GET` list rejects a sensitive field's value and directs you here. The response is a `{data, nextCursor}` envelope. Requires the `clients:r` scope.
     *
     * @param {Vectros.IdentityLookupRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.lookupClients({
     *         type: "person_v1",
     *         field: "ssn"
     *     })
     */
    public lookupClients(
        request: Vectros.IdentityLookupRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ClientPage> {
        return core.HttpResponsePromise.fromPromise(this.__lookupClients(request, requestOptions));
    }

    private async __lookupClients(
        request: Vectros.IdentityLookupRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ClientPage>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/clients/lookup",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ClientPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/clients/lookup");
    }

    /**
     * Returns the audit trail of changes to a client, newest first. Identity auditing is always on, so this history is always available; sensitive field values are redacted in each version. The response is a `{data, nextCursor}` envelope. Requires the `clients:r` scope.
     *
     * @param {Vectros.GetClientVersionsRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.identity.getClientVersions({
     *         id: "id"
     *     })
     */
    public getClientVersions(
        request: Vectros.GetClientVersionsRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ModelDataVersionPage> {
        return core.HttpResponsePromise.fromPromise(this.__getClientVersions(request, requestOptions));
    }

    private async __getClientVersions(
        request: Vectros.GetClientVersionsRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ModelDataVersionPage>> {
        const { id, startFrom } = request;
        const _queryParams: Record<string, unknown> = {
            startFrom,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/clients/${core.url.encodePathParam(id)}/versions`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ModelDataVersionPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/clients/{id}/versions");
    }

    /**
     * Returns a paginated list of organizations in your account. Filter by `userId` to return only the organizations owned by a specific user, or by `externalId` for an exact lookup using your own identifier. You can also query schema-declared lookup fields by supplying `type` and `field` together with one lookup mode (`value` for equality, `from`/`to` for a range, or `prefix`). Requires the `orgs:r` scope.
     *
     * @param {Vectros.ListOrgsRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.identity.listOrgs({
     *         userId: "550e8400-e29b-41d4-a716-446655440000",
     *         externalId: "clinic_001",
     *         startFrom: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
     *         type: "org_v1",
     *         field: "region",
     *         value: "us-east",
     *         prefix: "us-"
     *     })
     */
    public listOrgs(
        request: Vectros.ListOrgsRequest = {},
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.OrgPage> {
        return core.HttpResponsePromise.fromPromise(this.__listOrgs(request, requestOptions));
    }

    private async __listOrgs(
        request: Vectros.ListOrgsRequest = {},
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.OrgPage>> {
        const {
            userId,
            externalId,
            startFrom,
            limit,
            type: type_,
            field,
            value,
            from: from_,
            to,
            prefix,
            order,
        } = request;
        const _queryParams: Record<string, unknown> = {
            userId,
            externalId,
            startFrom,
            limit,
            type: type_,
            field,
            value,
            from: from_,
            to,
            prefix,
            order: order != null ? order : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/orgs",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.OrgPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VectrosError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/orgs");
    }

    /**
     * Creates a new organization in your account. This call is idempotent on `externalId`: if an organization with the same `externalId` already exists, the existing record is returned instead of creating a duplicate. Requires the `orgs:c` scope.
     *
     * @param {Vectros.OrgRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.createOrg({
     *         externalId: "clinic_001"
     *     })
     */
    public createOrg(
        request: Vectros.OrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.OrgResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createOrg(request, requestOptions));
    }

    private async __createOrg(
        request: Vectros.OrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.OrgResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/orgs",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.OrgResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/orgs");
    }

    /**
     * Retrieves a single organization by its Vectros-assigned ID, returning its current name, status, payload, and schema binding. Requires the `orgs:r` scope.
     *
     * @param {Vectros.GetOrgRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.identity.getOrg({
     *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
     *     })
     */
    public getOrg(
        request: Vectros.GetOrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.OrgResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getOrg(request, requestOptions));
    }

    private async __getOrg(
        request: Vectros.GetOrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.OrgResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/orgs/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.OrgResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/orgs/{id}");
    }

    /**
     * Updates the mutable fields of an organization. Omitted fields are preserved (a null value does not clear a field), and the `payload` object is replaced in full when supplied rather than deep-merged. Requires the `orgs:u` scope.
     *
     * @param {Vectros.UpdateOrgRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.updateOrg({
     *         id: "id",
     *         body: {
     *             externalId: "clinic_001"
     *         }
     *     })
     */
    public updateOrg(
        request: Vectros.UpdateOrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.OrgResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateOrg(request, requestOptions));
    }

    private async __updateOrg(
        request: Vectros.UpdateOrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.OrgResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/orgs/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.OrgResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/orgs/{id}");
    }

    /**
     * Permanently deletes an organization. This action cannot be undone. Requires the `orgs:d` scope.
     *
     * @param {Vectros.DeleteOrgRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.deleteOrg({
     *         id: "id"
     *     })
     */
    public deleteOrg(
        request: Vectros.DeleteOrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteOrg(request, requestOptions));
    }

    private async __deleteOrg(
        request: Vectros.DeleteOrgRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/orgs/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/orgs/{id}");
    }

    /**
     * Looks up organizations by a schema-declared field value, with the search criteria sent in the request body instead of the URL. Use this when looking up by a sensitive field: the value travels in the body and is never exposed in the URL. This is the body-based equivalent of the `type`/`field`/`value` lookup on `GET /v1/orgs`, which rejects sensitive-field values and directs you here. Returns a `{data, nextCursor}` envelope. Requires the `orgs:r` scope.
     *
     * @param {Vectros.IdentityLookupRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.lookupOrgs({
     *         type: "person_v1",
     *         field: "ssn"
     *     })
     */
    public lookupOrgs(
        request: Vectros.IdentityLookupRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.OrgPage> {
        return core.HttpResponsePromise.fromPromise(this.__lookupOrgs(request, requestOptions));
    }

    private async __lookupOrgs(
        request: Vectros.IdentityLookupRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.OrgPage>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/orgs/lookup",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.OrgPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/orgs/lookup");
    }

    /**
     * Returns the audit trail of changes made to an organization, newest first. Version history is always recorded for identity entities, and sensitive field values are redacted in the history. Requires the `orgs:r` scope.
     *
     * @param {Vectros.GetOrgVersionsRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.identity.getOrgVersions({
     *         id: "id"
     *     })
     */
    public getOrgVersions(
        request: Vectros.GetOrgVersionsRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ModelDataVersionPage> {
        return core.HttpResponsePromise.fromPromise(this.__getOrgVersions(request, requestOptions));
    }

    private async __getOrgVersions(
        request: Vectros.GetOrgVersionsRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ModelDataVersionPage>> {
        const { id, startFrom } = request;
        const _queryParams: Record<string, unknown> = {
            startFrom,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/orgs/${core.url.encodePathParam(id)}/versions`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ModelDataVersionPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/orgs/{id}/versions");
    }

    /**
     * Returns a paginated list of the users in your account. Pass `externalId` to look up a single user by your own identifier. To filter on schema-declared lookup fields, supply `type` and `field` together with one lookup mode: `value` (exact match), `from`+`to` (range), or `prefix`. Requires the `users:r` scope.
     *
     * @param {Vectros.ListUsersRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.identity.listUsers({
     *         externalId: "usr_12345",
     *         startFrom: "550e8400-e29b-41d4-a716-446655440000",
     *         type: "person_v1",
     *         field: "team",
     *         value: "engineering",
     *         prefix: "eng"
     *     })
     */
    public listUsers(
        request: Vectros.ListUsersRequest = {},
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.UserPage> {
        return core.HttpResponsePromise.fromPromise(this.__listUsers(request, requestOptions));
    }

    private async __listUsers(
        request: Vectros.ListUsersRequest = {},
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.UserPage>> {
        const { externalId, startFrom, limit, type: type_, field, value, from: from_, to, prefix, order } = request;
        const _queryParams: Record<string, unknown> = {
            externalId,
            startFrom,
            limit,
            type: type_,
            field,
            value,
            from: from_,
            to,
            prefix,
            order: order != null ? order : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/users",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.UserPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VectrosError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/users");
    }

    /**
     * Creates a user identity in your account. The operation is idempotent on `externalId`: if a user with the same `externalId` already exists, the existing record is returned instead of creating a duplicate. Requires the `users:c` scope.
     *
     * @param {Vectros.UserRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.createUser({
     *         externalId: "usr_12345"
     *     })
     */
    public createUser(
        request: Vectros.UserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.UserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createUser(request, requestOptions));
    }

    private async __createUser(
        request: Vectros.UserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.UserResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/users",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.UserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/users");
    }

    /**
     * Retrieves a single user by its Vectros-assigned ID. Requires the `users:r` scope.
     *
     * @param {Vectros.GetUserRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.identity.getUser({
     *         id: "550e8400-e29b-41d4-a716-446655440000"
     *     })
     */
    public getUser(
        request: Vectros.GetUserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.UserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getUser(request, requestOptions));
    }

    private async __getUser(
        request: Vectros.GetUserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.UserResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/users/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.UserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/users/{id}");
    }

    /**
     * Updates mutable fields on an existing user (such as email, status, payload, or schema binding). The `type` field is immutable after creation. This endpoint also activates an invited user: a PUT that moves a PENDING user to ACTIVE and carries `inviteToken`, `externalSubject`, and `emailVerifiedAttestation=true` completes the invitation. Requires the `users:u` scope.
     *
     * @param {Vectros.UpdateUserRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.updateUser({
     *         id: "550e8400-e29b-41d4-a716-446655440000",
     *         body: {
     *             externalId: "usr_12345"
     *         }
     *     })
     */
    public updateUser(
        request: Vectros.UpdateUserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.UserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateUser(request, requestOptions));
    }

    private async __updateUser(
        request: Vectros.UpdateUserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.UserResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/users/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.UserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v1/users/{id}");
    }

    /**
     * Permanently deletes a user identity. This cannot be undone. If the user is a pending invitation, the associated access profile created for that invitation is also removed. Requires the `users:d` scope.
     *
     * @param {Vectros.DeleteUserRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.deleteUser({
     *         id: "550e8400-e29b-41d4-a716-446655440000"
     *     })
     */
    public deleteUser(
        request: Vectros.DeleteUserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteUser(request, requestOptions));
    }

    private async __deleteUser(
        request: Vectros.DeleteUserRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/users/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v1/users/{id}");
    }

    /**
     * Looks up users by a schema lookup field, with the query criteria carried in the request body rather than the URL. Use this when looking up by a sensitive (blind-indexed) field: the value is blind-indexed server-side and never appears in the URL, request logs, or proxies. The query semantics are identical to the GET /v1/users lookup, which rejects sensitive-field values and directs you here. Returns a page in the `{data, nextCursor}` envelope. Requires the `users:r` scope.
     *
     * @param {Vectros.IdentityLookupRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.BadRequestError}
     * @throws {@link Vectros.TooManyRequestsError}
     *
     * @example
     *     await client.identity.lookupUsers({
     *         type: "person_v1",
     *         field: "ssn"
     *     })
     */
    public lookupUsers(
        request: Vectros.IdentityLookupRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.UserPage> {
        return core.HttpResponsePromise.fromPromise(this.__lookupUsers(request, requestOptions));
    }

    private async __lookupUsers(
        request: Vectros.IdentityLookupRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.UserPage>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/users/lookup",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.UserPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vectros.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Vectros.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/users/lookup");
    }

    /**
     * Returns the audit trail of changes to a user, most recent first. Identity history is always recorded and always available. Sensitive field values are redacted in every historical version. Returns a page in the `{data, nextCursor}` envelope. Requires the `users:r` scope.
     *
     * @param {Vectros.GetUserVersionsRequest} request
     * @param {IdentityClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vectros.NotFoundError}
     *
     * @example
     *     await client.identity.getUserVersions({
     *         id: "id"
     *     })
     */
    public getUserVersions(
        request: Vectros.GetUserVersionsRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): core.HttpResponsePromise<Vectros.ModelDataVersionPage> {
        return core.HttpResponsePromise.fromPromise(this.__getUserVersions(request, requestOptions));
    }

    private async __getUserVersions(
        request: Vectros.GetUserVersionsRequest,
        requestOptions?: IdentityClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vectros.ModelDataVersionPage>> {
        const { id, startFrom } = request;
        const _queryParams: Record<string, unknown> = {
            startFrom,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/users/${core.url.encodePathParam(id)}/versions`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vectros.ModelDataVersionPage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Vectros.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VectrosError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/users/{id}/versions");
    }
}
