// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "exp_550e8400e29b41d4a716446655440000"
 *     }
 */
export interface GetExportRequest {
    /** The id of the export job to poll, as returned when the job was submitted. */
    id: string;
}
