// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             name: "Patient Records 2024"
 *         }
 *     }
 */
export interface CreateFolderRequest {
    /** When `true`, if a folder with the same slug already exists under the same parent its mutable fields (`name`, `description`, and ownership) are overwritten from the request and the version is bumped, instead of the existing folder being returned unchanged; the immutable slug and parent are never changed. A re-applied upsert whose content matches is a no-op (no version bump). Defaults to `false`. Requires the `folders:u` scope in addition to `folders:c`. */
    upsert?: boolean;
    body: Vectros.FolderRequest;
}
