// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
 *     }
 */
export interface GetFolderVersionsRequest {
    /** The ID of the folder whose history you want. */
    id: string;
    /** Pagination cursor. Pass the `nextCursor` value from the previous page to fetch the next page; omit it for the first page. */
    startFrom?: string;
}
