// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             name: "Patient Records 2024"
 *         }
 *     }
 */
export interface PatchFolderRequest {
    id: string;
    body: Vectros.FolderRequest;
}
