// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         keyName: "research-bot production",
 *         tenantId: "ten_live_xxx",
 *         contextId: "myapp",
 *         userId: "alice-001"
 *     }
 */
export interface CreateScopedKeyRequest {
    /** A human-readable name for the key, used to identify and disambiguate multiple keys for the same user. Maximum 100 characters. */
    keyName: string;
    /** The tenant the key will operate on. Must be your live tenant ID or your test tenant ID; an ID outside your account returns a uniform `404 not found` (no distinction is made between a missing and an out-of-account tenant). */
    tenantId: string;
    /** The app context within the tenant. Must reference an app context that already exists (create one via `POST /v1/app-contexts`). */
    contextId: string;
    /** The user the key binds to. May be a `HUMAN` or a `SERVICE` user (a service user is the typical agent or bot case). An access profile must already exist for this context and user — the key references that profile; it does not create one. */
    userId: string;
    /** Optional display label surfaced through `/v1/ping` as `principalLabel`. The MCP `current_identity` tool uses it to show "signed in as ..." hints to end users (e.g. "Claude Desktop — clinical-notes RO"). Distinct from `keyName`, which is your own identifier for the key. Maximum 80 characters; if present, it must not have leading or trailing whitespace. */
    label?: string;
}
