// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         issuerId: "auth0-prod"
 *     }
 */
export interface DeleteIssuerRequest {
    /** The issuer's slug. */
    issuerId: string;
}
