// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subjectType: "user",
 *         subjectId: "user_abc123",
 *         contextId: "ctx_intake",
 *         clientId: "client_xyz789",
 *         action: "read",
 *         callerKeyId: "key_abc123",
 *         resourceType: "intake_form",
 *         resourceId: "rec_456"
 *     }
 */
export interface GetAccessLogRequest {
    /** Kind of subject to account for: `user`, `client`, or `org`. */
    subjectType?: string;
    /** Identifier of the data subject whose read history to return — the primary accounting-of-disclosures axis. Must be supplied together with `subjectType` (and a `contextId`). */
    subjectId?: string;
    /** Restrict results to a single app context (the data-partition axis). Required for a subject or record query. */
    contextId?: string;
    /** Further restrict a subject query to reads about a single nested client/patient. */
    clientId?: string;
    /** Start of the time window (ISO-8601 UTC, inclusive). */
    from?: string;
    /** End of the time window (ISO-8601 UTC, exclusive; defaults to now). */
    to?: string;
    /** Restrict to a single action: `read`, `list`, `lookup`, `search`, or `rag`. */
    action?: string;
    /** Forensic axis — restrict to reads performed by a single credential (the API key / scoped token key id that made the call). */
    callerKeyId?: string;
    /** Restrict to a single accessed resource type: a record schema type name, or one of `document`, `search`, or `rag`. */
    resourceType?: string;
    /** Forensic axis — restrict to reads of a single accessed record/document id. */
    resourceId?: string;
    /** If true, return only reads that actually revealed a sensitive value in plaintext. */
    revealedSensitive?: boolean;
    /** Opaque cursor from a previous page's `nextCursor`; pass it back to fetch the next page. */
    startFrom?: string;
    /** Maximum number of rows to return per page (1–500; defaults to 200). */
    limit?: number;
}
