// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contextId: "contextId",
 *         principalId: "principalId"
 *     }
 */
export interface GetAccessProfileRequest {
    contextId: string;
    principalId: string;
}
