// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contextId: "contextId",
 *         roleId: "roleId"
 *     }
 */
export interface GetRoleRequest {
    contextId: string;
    roleId: string;
}
