// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contextId: "myapp",
 *         roleId: "roleId"
 *     }
 */
export interface GetRoleVersionsRequest {
    /** Your identifier for the app context. */
    contextId: string;
    roleId: string;
    /** Pagination cursor. Pass the `nextCursor` value returned by the previous page to fetch the next page; omit it to start from the most recent versions. */
    startFrom?: string;
}
