// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contextId: "default"
 *     }
 */
export interface GetUsageRequest {
    /** Calendar year (for example, 2026). Defaults to the current year. */
    year?: number;
    /** Calendar month, 1-12 (for example, 5 for May). Defaults to the current month. */
    month?: number;
    /** App context id. When supplied, the `contexts` breakdown is restricted to that single app context; your account-wide totals are unaffected. */
    contextId?: string;
}
