// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         issuerId: "auth0-prod"
 *     }
 */
export interface IssuerUpdateRequest {
    /** The issuer's slug. */
    issuerId: string;
    /** Trust-anchor field — immutable. Present only so the current value may be echoed back without error; a differing value is rejected. */
    issuer?: string;
    /** Trust-anchor field — immutable. Present only so the current value may be echoed back without error; a differing value is rejected. */
    jwksUri?: string;
    /** Trust-anchor field — immutable. Present only so the current value may be echoed back without error; a differing value is rejected. */
    audience?: string;
    /** Routing-pin field — immutable. Present only so the current value may be echoed back without error; a differing value is rejected. */
    contextId?: string;
    /** Updatable, but NOT a "safe" field in the sense the others on this object are: it names which verified JWT claim becomes a federated user's internal identity key, so changing it re-identifies (or, under self-signup, orphans) every user already bound through this issuer. Refused with 400 once the issuer has ever bound a user; freely updatable before that, and supplying the current value back is always a no-op. Omit to leave unchanged. */
    subClaim?: string;
    /** Safe field — updatable. Omit to leave unchanged. */
    emailClaim?: string;
    /** Safe field — updatable. The IdP's OIDC userinfo endpoint, used as a fallback email-resolution source when `emailClaim` misses on the presented access token. Omit to leave unchanged. See `IssuerRequest.userinfoUri` for the full semantics. */
    userinfoUri?: string;
    /** Safe field — updatable. `active` or `suspended`. Setting `suspended` causes this issuer's tokens to be rejected at exchange time identically to an unregistered issuer — existing bound users are unaffected until they next need a fresh exchange. A registration in `pending_verification` accepts no status change at all (only its own current status echoed back is tolerated) — prove control of the issuer with `POST /v1/auth/issuers/{issuerId}/verify` first — and `pending_verification` itself can never be set. Omit to leave unchanged. */
    status?: string;
    /** Safe field — updatable. Omit to leave unchanged; pass an empty list to disable self-signup entirely. See `IssuerRequest.selfSignupPolicies` for the full semantics — the same elevated-role restriction applies here. */
    selfSignupPolicies?: Vectros.SelfSignupPolicy[];
    /** Safe field — updatable. Omit to leave unchanged; pass an empty list to stop capturing any claim beyond email. See `IssuerRequest.capturedClaims` for the full semantics. */
    capturedClaims?: string[];
    /** Safe field — updatable. A NEW non-blank value must already be a VERIFIED domain for your account (same requirement as at registration); an empty string clears this issuer to domain-less (unrestricted), and is refused with 400 unless this registration holds the unrestricted (issuer, audience) pair. A registration holds it if it was registered without a domain and then verified (it keeps it if later scoped to a domain); a registration created scoped to a domain never holds it, and neither does an older registration that predates pair claims. To get an unrestricted issuer in that case, delete the scoped registration, register a new issuer without `restrictedToDomain`, and verify it. An app context holds one issuer registration at a time, of any status, so a replacement in the same context is possible only after the delete succeeds. A registration that any user was created or matched through cannot be deleted (409): register the replacement under a different app context, which does not carry over the old context's users, roles or access profiles. A registration awaiting verification cannot be re-scoped. Omit to leave unchanged. See `IssuerRequest.restrictedToDomain` for the full semantics, including why this field is updatable while issuer/jwksUri/audience/contextId are not. */
    restrictedToDomain?: string;
}
