// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         issuerId: "auth0-prod",
 *         issuer: "https://your-tenant.us.auth0.com/",
 *         jwksUri: "https://your-tenant.us.auth0.com/.well-known/jwks.json",
 *         audience: "https://api.your-app.example.com",
 *         contextId: "casework"
 *     }
 */
export interface IssuerRequest {
    /** Short slug identifying this issuer within your tenant: 3-31 characters, a lowercase letter first, then lowercase letters, digits, or hyphens. Immutable once registered. */
    issuerId: string;
    /** The IdP's `iss` claim value, exactly as it appears in tokens it issues. */
    issuer: string;
    /** The IdP's remote JWKS endpoint, used to verify presented tokens' signatures. Must use the https:// scheme — an http:// endpoint is refused, since a plaintext fetch lets an on-path attacker substitute the signing keys this platform trusts for the issuer. */
    jwksUri: string;
    /** The `aud` claim value this contract requires a presented subject_token to carry. Must be globally unique in combination with `issuer` — use a distinct audience per environment/context sharing one IdP account (most OIDC providers support this as an ordinary per-API/application default). */
    audience: string;
    /** Which of your app contexts an exchanged token targets. Must be an existing app context (create it first via `POST /v1/app-contexts`). A credential authorized via the CLI bootstrap's provisioning capability may only name the app context it is itself bound to; naming another one is refused. A root API key may name any of its contexts. */
    contextId: string;
    /** The claim in the IdP's token that carries the subject identifier. Defaults to `sub` if omitted. */
    subClaim?: string;
    /** The claim in the IdP's token that carries the subject's email, used for first-login invite matching. Defaults to `email` if omitted. */
    emailClaim?: string;
    /** The IdP's OIDC userinfo endpoint. Optional. Presented tokens are access tokens, which under OIDC don't carry `email` unless the IdP was specifically configured to add it — if `emailClaim` misses on the presented token, and `userinfoUri` is configured, Vectros falls back to calling this endpoint (with the presented token as the bearer credential) and reads `emailClaim` from its JSON response instead. Omit to leave the fallback disabled — a token that doesn't carry the configured email claim then fails first-login exactly as it does today. Must use the https:// scheme — an http:// endpoint is refused, since the request carries your presented token as a bearer credential and a plaintext fetch lets an on-path attacker both harvest it and control the response this platform trusts back. */
    userinfoUri?: string;
    /** Opt-in self-service signup: a list of {signup_type, role_id} pairs. When a first-time exchange caller presents no invite token but names a signup_type matching one of these (or omits signup_type and exactly one entry exists), a brand-new user is created and bound to that entry's role — no invite required. Every entry must, by construction, be something you're willing to grant to ANY caller who can present a token from this issuer: no entry may target a role carrying elevated (provisioning or wildcard) scope — rejected. Omit entirely to leave self-signup disabled (the default). */
    selfSignupPolicies?: Vectros.SelfSignupPolicy[];
    /** Opt-in additional identity-claim capture. A list of OIDC claim names — beyond `emailClaim`, which keeps its own dedicated field — to capture from this issuer's tokens on every successful token exchange and store as your tenant's golden IdP-asserted identity copy. Not a fixed set: name whatever claims this IdP actually asserts (standard, e.g. `name`/`phone_number`/`address`, or your IdP's own custom claims). Each claim is read from the verified token first, falling back to `userinfoUri` (if configured) only for names still missing after that. Omit entirely to capture nothing beyond email (the default). */
    capturedClaims?: string[];
    /** Opt-in domain-capture proof of issuer control. When set, this registration's (issuer, audience) uniqueness is scoped to this specific domain rather than the bare pair, so a registration for a domain you can prove you own is never blocked by an unrelated existing registration on the same (issuer, audience) pair. REQUIRES a VERIFIED domain for your partner account, proven via the SEPARATE, OWNER-authenticated developer portal (POST /developer/domains, then /verify — a Cognito-OWNER-gated surface, not reachable with this same partner-API credential; your account owner verifies the domain once, then this field references it by name) — registration is refused with 400 if the domain isn't already verified. At token-exchange time, this issuer's tokens are matched only when they carry an `hd` claim equal to this domain (the OIDC hosted-domain convention — Google emits this natively for Workspace/Cloud-org accounts; other IdPs need a claims-mapping rule configured to emit a claim literally named `hd`). Updatable later via PUT (unlike issuer/jwksUri/audience/contextId) — changing it never re-points an already-bound user's trust anchor or identity, only future routing eligibility; see `IssuerUpdateRequest.restrictedToDomain`. Omit to leave this issuer domain-less (the current, unrestricted behavior) — required for a shared/consumer IdP with no company-domain population, but note that population is NOT protected by proof-of-control: with no `hd` claim in a presented token, only a domain-less registration can ever match, exactly as today. */
    restrictedToDomain?: string;
}
