// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         issuerId: "auth0-prod",
 *         issuer: "https://your-tenant.us.auth0.com/",
 *         jwksUri: "https://your-tenant.us.auth0.com/.well-known/jwks.json",
 *         audience: "https://api.your-app.example.com",
 *         contextId: "casework"
 *     }
 */
export interface IssuerRequest {
    /** Short slug identifying this issuer within your tenant: 3-31 characters, a lowercase letter first, then lowercase letters, digits, or hyphens. Immutable once registered. */
    issuerId: string;
    /** The IdP's `iss` claim value, exactly as it appears in tokens it issues. */
    issuer: string;
    /** The IdP's remote JWKS endpoint, used to verify presented tokens' signatures. */
    jwksUri: string;
    /** The `aud` claim value this contract requires a presented subject_token to carry. Must be globally unique in combination with `issuer` — use a distinct audience per environment/context sharing one IdP account (most OIDC providers support this as an ordinary per-API/application default). */
    audience: string;
    /** Which of your app contexts an exchanged token targets. Must be an existing app context (create it first via `POST /v1/app-contexts`). A credential authorized via the CLI bootstrap's provisioning capability may only name the app context it is itself bound to; naming another one is refused. A root API key may name any of its contexts. */
    contextId: string;
    /** The claim in the IdP's token that carries the subject identifier. Defaults to `sub` if omitted. */
    subClaim?: string;
    /** The claim in the IdP's token that carries the subject's email, used for first-login invite matching. Defaults to `email` if omitted. */
    emailClaim?: string;
    /** Opt-in self-service signup: a list of {signup_type, role_id} pairs. When a first-time exchange caller presents no invite token but names a signup_type matching one of these (or omits signup_type and exactly one entry exists), a brand-new user is created and bound to that entry's role — no invite required. Every entry must, by construction, be something you're willing to grant to ANY caller who can present a token from this issuer: no entry may target a role carrying elevated (provisioning or wildcard) scope — rejected. Omit entirely to leave self-signup disabled (the default). */
    selfSignupPolicies?: Vectros.SelfSignupPolicy[];
}
