// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListIssuersRequest {
    /** Pagination cursor from a previous page's `nextCursor`. */
    startFrom?: string;
    /** Maximum registrations per page (1-100; defaults to 20). */
    limit?: number;
}
