// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         userId: "550e8400-e29b-41d4-a716-446655440000",
 *         scope: {
 *             allowedActions: ["records:crud", "schemas:r"],
 *             identity: {
 *                 "userId": "550e8400-e29b-41d4-a716-446655440000"
 *             },
 *             dataScope: {
 *                 "scope:org": ["6ba7b810-9dad-11d1-80b4-00c04fd430c8"]
 *             }
 *         },
 *         expiresInSeconds: 3600
 *     }
 */
export interface TokenRequest {
    /** The Vectros user ID of the end user this token is minted for. This is the UUID returned when you created the user via `POST /v1/users`. Optional — omit it for service-to-service tokens that have no specific user context. If provided, it must reference a real user in your account. Use `GET /v1/users?externalId={yourId}` to resolve your own system's user ID to the Vectros user ID. */
    userId?: string;
    /** The app context to mint the token into. Optional — omit it to inherit your own credential's context (a root API key defaults to `default`). Must reference an app context that already exists in your tenant (create one via `POST /v1/app-contexts`); an unrecognized value returns a uniform `404 not found`. Only meaningful for root API key callers — this endpoint is root-key-only, so there is no confined credential this could let reach a context it doesn't hold. */
    contextId?: string;
    scope: Vectros.ScopeRequest;
    /** How long the token remains valid, in seconds. Maximum 3600 (1 hour), which is also the default. */
    expiresInSeconds?: number;
}
