// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         contextId: "contextId",
 *         roleId: "roleId",
 *         body: {
 *             roleId: "engineering-member",
 *             name: "Engineering Team Member",
 *             scopes: [{
 *                     allowed_actions: ["read", "write"]
 *                 }]
 *         }
 *     }
 */
export interface UpdateRoleRequest {
    contextId: string;
    roleId: string;
    body: Vectros.RoleRequest;
}
