// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             externalId: "clinic_001"
 *         }
 *     }
 */
export interface CreateOrgRequest {
    /** When `true`, if an organization with the same `externalId` already exists its mutable fields are overwritten (the submitted `name`/`status`/`payload`/`schemaId` are applied) instead of being returned unchanged; the immutable `externalId` and ownership are never changed. A re-applied upsert whose content matches is a no-op. Defaults to `false`. Requires the `orgs:u` scope in addition to `orgs:c`. */
    upsert?: boolean;
    body: Vectros.OrgRequest;
}
