// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             externalId: "patient_789"
 *         }
 *     }
 */
export interface CreateClientRequest {
    /** When `true`, if a client with the same `externalId` already exists its mutable fields are overwritten (the submitted `name`/`status`/`payload`/`orgId`/`schemaId` are applied) instead of being returned unchanged; the immutable `externalId` and ownership are never changed. A re-applied upsert whose content matches is a no-op. Defaults to `false`. Requires the `clients:u` scope in addition to `clients:c`. */
    upsert?: boolean;
    body: Vectros.ClientRequest;
}
