// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace: "team",
 *         id: "id"
 *     }
 */
export interface DeleteEntityRequest {
    /** The entity namespace. */
    namespace: string;
    id: string;
}
