// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetClientVersionsRequest {
    /** The Vectros-assigned UUID of the client whose history you want. */
    id: string;
    /** Pagination cursor. Pass the `nextCursor` from the previous page to fetch the next page; omit it for the first page. */
    startFrom?: string;
}
