// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace: "team",
 *         id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
 *     }
 */
export interface GetEntityRequest {
    /** The entity namespace. */
    namespace: string;
    /** The Vectros-assigned ID (UUID) of the entity. */
    id: string;
}
