// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace: "team"
 *     }
 */
export interface ListEntitiesRequest {
    /** The entity namespace. */
    namespace: string;
    /** Return only entities owned by this user (Vectros user ID). */
    userId?: string;
    /** Look up an entity by your own identifier. Returns a list with the single match, or empty. */
    externalId?: string;
    /** Filter by parent edge as `<namespace>:<value>` (e.g. `org:6ba7...`). Matches any of the entity's parents, not just its first. Naming this route's own namespace resolves the entity itself. */
    scope?: string;
    /** Schema record type whose lookup fields you want to query. Supply with `field` and one lookup mode (`value`, `from`/`to`, or `prefix`). */
    type?: string;
    /** The schema-declared lookup field to filter on. Supply with `type` and one lookup mode. */
    field?: string;
    /** Exact value to match for `field` (equality). Not allowed for a sensitive field — use `POST /v1/entities/{namespace}/lookup`. */
    value?: string;
    /** Inclusive lower bound for a range lookup (requires `to`; range-enabled fields). */
    from?: string;
    /** Inclusive upper bound for a range lookup (requires `from`). */
    to?: string;
    /** Match all values of `field` starting with this prefix (range-enabled string fields). */
    prefix?: string;
    /** Sort direction by the field's value for a `type`/`field` lookup: `asc` (ascending, the default) or `desc`. Lookup mode only — listing by namespace, `userId`, `scope`, or `externalId` does not take a sort direction and rejects this parameter. */
    order?: Vectros.ListEntitiesRequestOrder;
    /** Pagination cursor from a previous page's `nextCursor`. */
    startFrom?: string;
    /** Maximum entities per page (1-100; defaults to 20). */
    limit?: number;
}
