// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListNamespacesRequest {
    /** Pagination cursor from a previous page's `nextCursor`. */
    startFrom?: string;
    /** Maximum registrations per page (1-100; defaults to 20). */
    limit?: number;
    /** List one app context's OWN registrations instead of the tenant-wide ones. Omit for the tenant-wide registrations only — a context's own registrations are never mixed into the unfiltered listing. */
    contextId?: string;
}
