// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         userId: "550e8400-e29b-41d4-a716-446655440000",
 *         externalId: "clinic_001",
 *         startFrom: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
 *         type: "org_v1",
 *         field: "region",
 *         value: "us-east",
 *         prefix: "us-"
 *     }
 */
export interface ListOrgsRequest {
    /** Return only organizations owned by this user, given as the Vectros-assigned ID (UUID) of a user. To resolve a user ID from your own identifier, call `GET /v1/users?externalId=`. */
    userId?: string;
    /** Look up an organization by your own identifier. Returns a list with the single matching organization, or an empty list if none matches. */
    externalId?: string;
    /** Pagination cursor. Pass the `nextCursor` from the previous page to fetch the next page; omit it for the first page. */
    startFrom?: string;
    /** Maximum number of organizations to return per page (1–100; defaults to 20). */
    limit?: number;
    /** The schema record type whose lookup fields you want to query. Must be supplied together with `field` and exactly one lookup mode (`value`, `from`/`to`, or `prefix`). */
    type?: string;
    /** The schema-declared lookup field to filter on. Must be one of the lookup fields defined on the schema named by `type`. Supplied together with `type` and one lookup mode. */
    field?: string;
    /** Exact value to match for `field` (equality lookup). Mutually exclusive with `from`/`to` and `prefix`. Not allowed for a sensitive field — use `POST /v1/orgs/lookup` instead so the value is not exposed in the URL. */
    value?: string;
    /** Inclusive lower bound for a range lookup. Requires `to`, and is only supported on non-sensitive fields that have range lookups enabled. Mutually exclusive with `value` and `prefix`. */
    from?: string;
    /** Inclusive upper bound for a range lookup. Requires `from`. */
    to?: string;
    /** Match all values for `field` that start with this prefix. Only supported on string fields that have range lookups enabled. Mutually exclusive with `value` and `from`/`to`. */
    prefix?: string;
    /** Sort direction for lookup results: `asc` (ascending, the default) or `desc` (descending). */
    order?: Vectros.ListOrgsRequestOrder;
}
