// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             namespace: "team",
 *             specificityRank: 1500
 *         }
 *     }
 */
export interface RegisterNamespaceRequest {
    /** The app context to own this registration. Omit for a TENANT-WIDE registration visible to every context. */
    contextId?: string;
    body: Vectros.NamespaceRequest;
}
