// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             externalId: "patient_789"
 *         }
 *     }
 */
export interface UpdateClientRequest {
    id: string;
    body: Vectros.ClientRequest;
}
