// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace: "team",
 *         id: "id",
 *         body: {
 *             externalId: "team_eng_platform"
 *         }
 *     }
 */
export interface UpdateEntityRequest {
    /** The entity namespace. */
    namespace: string;
    id: string;
    body: Vectros.EntityRequest;
}
