// This file was auto-generated by Fern from our API Definition.

import type * as Vectros from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace: "team",
 *         body: {
 *             namespace: "team",
 *             specificityRank: 1500
 *         }
 *     }
 */
export interface UpdateNamespaceRequest {
    /** The namespace name. */
    namespace: string;
    body: Vectros.NamespaceRequest;
}
