// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "user@example.com",
 *         contextId: "myapp"
 *     }
 */
export interface UserExistsByEmailRequest {
    /** The email address to check. Matched case-insensitively. */
    email?: string;
    /** The app context to check membership in. A context-confined credential (a scoped token or key bound to one context) may only name its own bound context — naming any other context is rejected with a uniform 403, before the existence check runs. */
    contextId?: string;
}
